export interface Icon {
  id: string;
  name: string;
  svg: string;
  jsx: string;
  category: string;
}

export const icons: Icon[] = [
  {
    id: "ac-fill",
    name: "Ac Fill",
    svg: `<i class="icon-ac-fill"></i>`,
    jsx: '<i className="icon-ac-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "ac-line",
    name: "Ac Line",
    svg: `<i class="icon-ac-line"></i>`,
    jsx: '<i className="icon-ac-line"></i>',
    category: "Accommodation",
  },
  {
    id: "adapter-fill",
    name: "Adapter Fill",
    svg: `<i class="icon-adapter-fill"></i>`,
    jsx: '<i className="icon-adapter-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "adapter-line",
    name: "Adapter Line",
    svg: `<i class="icon-adapter-line"></i>`,
    jsx: '<i className="icon-adapter-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "adjoining-room-fill",
    name: "Adjoining Room Fill",
    svg: `<i class="icon-adjoining-room-fill"></i>`,
    jsx: '<i className="icon-adjoining-room-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "adjoining-room-line",
    name: "Adjoining Room Line",
    svg: `<i class="icon-adjoining-room-line"></i>`,
    jsx: '<i className="icon-adjoining-room-line"></i>',
    category: "Accommodation",
  },
  {
    id: "aerobics-fill",
    name: "Aerobics Fill",
    svg: `<i class="icon-aerobics-fill"></i>`,
    jsx: '<i className="icon-aerobics-fill"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "aerobics-line",
    name: "Aerobics Line",
    svg: `<i class="icon-aerobics-line"></i>`,
    jsx: '<i className="icon-aerobics-line"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "air-filter-fill",
    name: "Air Filter Fill",
    svg: `<i class="icon-air-filter-fill"></i>`,
    jsx: '<i className="icon-air-filter-fill"></i>',
    category: "Facilities",
  },
  {
    id: "air-filter-line",
    name: "Air Filter Line",
    svg: `<i class="icon-air-filter-line"></i>`,
    jsx: '<i className="icon-air-filter-line"></i>',
    category: "Facilities",
  },
  {
    id: "alarm-fill",
    name: "Alarm Fill",
    svg: `<i class="icon-alarm-fill"></i>`,
    jsx: '<i className="icon-alarm-fill"></i>',
    category: "Services",
  },
  {
    id: "alarm-line",
    name: "Alarm Line",
    svg: `<i class="icon-alarm-line"></i>`,
    jsx: '<i className="icon-alarm-line"></i>',
    category: "Services",
  },
  {
    id: "atm-fill",
    name: "Atm Fill",
    svg: `<i class="icon-atm-fill"></i>`,
    jsx: '<i className="icon-atm-fill"></i>',
    category: "Services",
  },
  {
    id: "area-fill",
    name: "Area Fill",
    svg: `<i class="icon-area-fill"></i>`,
    jsx: '<i className="icon-area-fill"></i>',
    category: "Facilities",
  },
  {
    id: "area-line",
    name: "Area Line",
    svg: `<i class="icon-area-line"></i>`,
    jsx: '<i className="icon-area-line"></i>',
    category: "Facilities",
  },
  {
    id: "atm-line",
    name: "Atm Line",
    svg: `<i class="icon-atm-line"></i>`,
    jsx: '<i className="icon-atm-line"></i>',
    category: "Services",
  },
  {
    id: "baby-dress-fill",
    name: "Baby Dress Fill",
    svg: `<i class="icon-baby-dress-fill"></i>`,
    jsx: '<i className="icon-baby-dress-fill"></i>',
    category: "Shopping",
  },
  {
    id: "baby-dress-line",
    name: "Baby Dress Line",
    svg: `<i class="icon-baby-dress-line"></i>`,
    jsx: '<i className="icon-baby-dress-line"></i>',
    category: "Shopping",
  },
  {
    id: "baby-fill",
    name: "Baby Fill",
    svg: `<i class="icon-baby-fill"></i>`,
    jsx: '<i className="icon-baby-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "baby-line",
    name: "Baby Line",
    svg: `<i class="icon-baby-line"></i>`,
    jsx: '<i className="icon-baby-line"></i>',
    category: "Health & Others",
  },
  {
    id: "baby-slash-fill",
    name: "Baby Slash Fill",
    svg: `<i class="icon-baby-slash-fill"></i>`,
    jsx: '<i className="icon-baby-slash-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "baby-slash-line",
    name: "Baby Slash Line",
    svg: `<i class="icon-baby-slash-line"></i>`,
    jsx: '<i className="icon-baby-slash-line"></i>',
    category: "Health & Others",
  },
  {
    id: "balcony-fill",
    name: "Balcony Fill",
    svg: `<i class="icon-balcony-fill"></i>`,
    jsx: '<i className="icon-balcony-fill"></i>',
    category: "Facilities",
  },
  {
    id: "balcony-line",
    name: "Balcony Line",
    svg: `<i class="icon-balcony-line"></i>`,
    jsx: '<i className="icon-balcony-line"></i>',
    category: "Facilities",
  },
  {
    id: "ball-fill",
    name: "Ball Fill",
    svg: `<i class="icon-ball-fill"></i>`,
    jsx: '<i className="icon-ball-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "ball-line",
    name: "Ball Line",
    svg: `<i class="icon-ball-line"></i>`,
    jsx: '<i className="icon-ball-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "bank-fill",
    name: "Bank Fill",
    svg: `<i class="icon-bank-fill"></i>`,
    jsx: '<i className="icon-bank-fill"></i>',
    category: "Finance",
  },
  {
    id: "bank-line",
    name: "Bank Line",
    svg: `<i class="icon-bank-line"></i>`,
    jsx: '<i className="icon-bank-line"></i>',
    category: "Finance",
  },
  {
    id: "bar-fill",
    name: "Bar Fill",
    svg: `<i class="icon-bar-fill"></i>`,
    jsx: '<i className="icon-bar-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "bar-line",
    name: "Bar Line",
    svg: `<i class="icon-bar-line"></i>`,
    jsx: '<i className="icon-bar-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "basket-fill",
    name: "Basket Fill",
    svg: `<i class="icon-basket-fill"></i>`,
    jsx: '<i className="icon-basket-fill"></i>',
    category: "Shopping",
  },
  {
    id: "basket-line",
    name: "Basket Line",
    svg: `<i class="icon-basket-line"></i>`,
    jsx: '<i className="icon-basket-line"></i>',
    category: "Shopping",
  },
  {
    id: "bathrobe-fill",
    name: "Bathrobe Fill",
    svg: `<i class="icon-bathrobe-fill"></i>`,
    jsx: '<i className="icon-bathrobe-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "bathrobe-line",
    name: "Bathrobe Line",
    svg: `<i class="icon-bathrobe-line"></i>`,
    jsx: '<i className="icon-bathrobe-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "bbq-fill",
    name: "Bbq Fill",
    svg: `<i class="icon-bbq-fill"></i>`,
    jsx: '<i className="icon-bbq-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "bbq-line",
    name: "Bbq Line",
    svg: `<i class="icon-bbq-line"></i>`,
    jsx: '<i className="icon-bbq-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "beach-fill",
    name: "Beach Fill",
    svg: `<i class="icon-beach-fill"></i>`,
    jsx: '<i className="icon-beach-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "beach-line",
    name: "Beach Line",
    svg: `<i class="icon-beach-line"></i>`,
    jsx: '<i className="icon-beach-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "bed-fill",
    name: "Bed Fill",
    svg: `<i class="icon-bed-fill"></i>`,
    jsx: '<i className="icon-bed-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "bed-line",
    name: "Bed Line",
    svg: `<i class="icon-bed-line"></i>`,
    jsx: '<i className="icon-bed-line"></i>',
    category: "Accommodation",
  },
  {
    id: "bell-boy-fill",
    name: "Bell Boy Fill",
    svg: `<i class="icon-bell-boy-fill"></i>`,
    jsx: '<i className="icon-bell-boy-fill"></i>',
    category: "Services",
  },
  {
    id: "bell-boy-line",
    name: "Bell Boy Line",
    svg: `<i class="icon-bell-boy-line"></i>`,
    jsx: '<i className="icon-bell-boy-line"></i>',
    category: "Services",
  },
  {
    id: "bike-fill",
    name: "Bike Fill",
    svg: `<i class="icon-bike-fill"></i>`,
    jsx: '<i className="icon-bike-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "bike-line",
    name: "Bike Line",
    svg: `<i class="icon-bike-line"></i>`,
    jsx: '<i className="icon-bike-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "bill-fill",
    name: "Bill Fill",
    svg: `<i class="icon-bill-fill"></i>`,
    jsx: '<i className="icon-bill-fill"></i>',
    category: "Finance",
  },
  {
    id: "bill-line",
    name: "Bill Line",
    svg: `<i class="icon-bill-line"></i>`,
    jsx: '<i className="icon-bill-line"></i>',
    category: "Finance",
  },
  {
    id: "billiards-fill",
    name: "Billiards Fill",
    svg: `<i class="icon-billiards-fill"></i>`,
    jsx: '<i className="icon-billiards-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "billiards-line",
    name: "Billiards Line",
    svg: `<i class="icon-billiards-line"></i>`,
    jsx: '<i className="icon-billiards-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "bin-fill",
    name: "Bin Fill",
    svg: `<i class="icon-bin-fill"></i>`,
    jsx: '<i className="icon-bin-fill"></i>',
    category: "Facilities",
  },
  {
    id: "bin-line",
    name: "Bin Line",
    svg: `<i class="icon-bin-line"></i>`,
    jsx: '<i className="icon-bin-line"></i>',
    category: "Facilities",
  },
  {
    id: "bingo-fill",
    name: "Bingo Fill",
    svg: `<i class="icon-bingo-fill"></i>`,
    jsx: '<i className="icon-bingo-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "bingo-line",
    name: "Bingo Line",
    svg: `<i class="icon-bingo-line"></i>`,
    jsx: '<i className="icon-bingo-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "blanket-fill",
    name: "Blanket Fill",
    svg: `<i class="icon-blanket-fill"></i>`,
    jsx: '<i className="icon-blanket-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "blanket-line",
    name: "Blanket Line",
    svg: `<i class="icon-blanket-line"></i>`,
    jsx: '<i className="icon-blanket-line"></i>',
    category: "Accommodation",
  },
  {
    id: "boat-fill",
    name: "Boat Fill",
    svg: `<i class="icon-boat-fill"></i>`,
    jsx: '<i className="icon-boat-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "boat-line",
    name: "Boat Line",
    svg: `<i class="icon-boat-line"></i>`,
    jsx: '<i className="icon-boat-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "bon-fire-fill",
    name: "Bon Fire Fill",
    svg: `<i class="icon-bon-fire-fill"></i>`,
    jsx: '<i className="icon-bon-fire-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "bon-fire-line",
    name: "Bon Fire Line",
    svg: `<i class="icon-bon-fire-line"></i>`,
    jsx: '<i className="icon-bon-fire-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "books-fill",
    name: "Books Fill",
    svg: `<i class="icon-books-fill"></i>`,
    jsx: '<i className="icon-books-fill"></i>',
    category: "Misc",
  },
  {
    id: "books-line",
    name: "Books Line",
    svg: `<i class="icon-books-line"></i>`,
    jsx: '<i className="icon-books-line"></i>',
    category: "Misc",
  },
  {
    id: "bowl fill",
    name: "Bowl Fill",
    svg: `<i class="icon-bowl-fill"></i>`,
    jsx: '<i className="icon-bowl-fill"></i>',
    category: "Misc",
  },
  {
    id: "bowl-line",
    name: "Bowl Line",
    svg: `<i class="icon-bowl-line"></i>`,
    jsx: '<i className="icon-bowl-line"></i>',
    category: "Misc",
  },
  {
    id: "box-fill",
    name: "Box Fill",
    svg: `<i class="icon-box-fill"></i>`,
    jsx: '<i className="icon-box-fill"></i>',
    category: "Misc",
  },
  {
    id: "box-line",
    name: "Box Line",
    svg: `<i class="icon-box-line"></i>`,
    jsx: '<i className="icon-box-line"></i>',
    category: "Misc",
  },
  {
    id: "briefcase-fill",
    name: "Briefcase Fill",
    svg: `<i class="icon-briefcase-fill"></i>`,
    jsx: '<i className="icon-briefcase-fill"></i>',
    category: "Misc",
  },
  {
    id: "briefcase-line",
    name: "Briefcase Line",
    svg: `<i class="icon-briefcase-line"></i>`,
    jsx: '<i className="icon-briefcase-line"></i>',
    category: "Misc",
  },
  {
    id: "broom-fill",
    name: "Broom Fill",
    svg: `<i class="icon-broom-fill"></i>`,
    jsx: '<i className="icon-broom-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "broom-line",
    name: "Broom Line",
    svg: `<i class="icon-broom-line"></i>`,
    jsx: '<i className="icon-broom-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "building-fill",
    name: "Building Fill",
    svg: `<i class="icon-building-fill"></i>`,
    jsx: '<i className="icon-building-fill"></i>',
    category: "Facilities",
  },
  {
    id: "building-line",
    name: "Building Line",
    svg: `<i class="icon-building-line"></i>`,
    jsx: '<i className="icon-building-line"></i>',
    category: "Facilities",
  },
  {
    id: "burger-fill",
    name: "Burger Fill",
    svg: `<i class="icon-burger-fill"></i>`,
    jsx: '<i className="icon-burger-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "burger-line",
    name: "Burger Line",
    svg: `<i class="icon-burger-line"></i>`,
    jsx: '<i className="icon-burger-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "bus-fill",
    name: "Bus Fill",
    svg: `<i class="icon-bus-fill"></i>`,
    jsx: '<i className="icon-bus-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "bus-line",
    name: "Bus Line",
    svg: `<i class="icon-bus-line"></i>`,
    jsx: '<i className="icon-bus-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "cab-fill",
    name: "Cab Fill",
    svg: `<i class="icon-cab-fill"></i>`,
    jsx: '<i className="icon-cab-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "cab-line",
    name: "Cab Line",
    svg: `<i class="icon-cab-line"></i>`,
    jsx: '<i className="icon-cab-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "call-bell-fill",
    name: "Call Bell Fill",
    svg: `<i class="icon-call-bell-fill\"></i>`,
    jsx: '<i className="icon-call-bell-fill"></i>',
    category: "Services",
  },
  {
    id: "call-bell-line",
    name: "Call Bell Line",
    svg: `<i class="icon-call-bell-line\"></i>`,
    jsx: '<i className="icon-call-bell-line"></i>',
    category: "Services",
  },
  {
    id: "cards-fill",
    name: "Cards Fill",
    svg: `<i class="icon-cards-fill"></i>`,
    jsx: '<i className="icon-cards-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "cards-line",
    name: "Cards Line",
    svg: `<i class="icon-cards-line"></i>`,
    jsx: '<i className="icon-cards-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "carpet-fill",
    name: "Carpet Fill",
    svg: `<i class="icon-carpet-fill"></i>`,
    jsx: '<i className="icon-carpet-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "carpet-line",
    name: "Carpet Line",
    svg: `<i class="icon-carpet-line"></i>`,
    jsx: '<i className="icon-carpet-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "catering-fill",
    name: "Catering Fill",
    svg: `<i class="icon-catering-fill"></i>`,
    jsx: '<i className="icon-catering-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "catering-line",
    name: "Catering Line",
    svg: `<i class="icon-catering-line"></i>`,
    jsx: '<i className="icon-catering-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "cctv-fill",
    name: "CCTV Fill",
    svg: `<i class="icon-cctv-fill"></i>`,
    jsx: '<i className="icon-cctv-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "cctv-line",
    name: "CCTV Line",
    svg: `<i class="icon-cctv-line"></i>`,
    jsx: '<i className="icon-cctv-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "cell-fill",
    name: "Cell Fill",
    svg: `<i class="icon-cell-fill"></i>`,
    jsx: '<i className="icon-cell-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "cell-line",
    name: "Cell Line",
    svg: `<i class="icon-cell-line"></i>`,
    jsx: '<i className="icon-cell-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "chair-fill",
    name: "Chair Fill",
    svg: `<i class="icon-chair-fill"></i>`,
    jsx: '<i className="icon-chair-fill"></i>',
    category: "Furniture",
  },
  {
    id: "chair-line",
    name: "Chair Line",
    svg: `<i class="icon-chair-line"></i>`,
    jsx: '<i className="icon-chair-line"></i>',
    category: "Furniture",
  },
  {
    id: "charging-station-fill",
    name: "Charging Station Fill",
    svg: `<i class="icon-charging-station-fill"></i>`,
    jsx: '<i className="icon-charging-station-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "charging-station-line",
    name: "Charging Station Line",
    svg: `<i class="icon-charging-station-line"></i>`,
    jsx: '<i className="icon-charging-station-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "chef-hat-fill",
    name: "Chef Hat Fill",
    svg: `<i class="icon-chef-hat-fill"></i>`,
    jsx: '<i className="icon-chef-hat-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "chef-hat-line",
    name: "Chef Hat Line",
    svg: `<i class="icon-chef-hat-line"></i>`,
    jsx: '<i className="icon-chef-hat-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "cheque-fill",
    name: "Cheque Fill",
    svg: `<i class="icon-cheque-fill"></i>`,
    jsx: '<i className="icon-cheque-fill"></i>',
    category: "Finance",
  },
  {
    id: "cheque-line",
    name: "Cheque Line",
    svg: `<i class="icon-cheque-line"></i>`,
    jsx: '<i className="icon-cheque-line"></i>',
    category: "Finance",
  },
  {
    id: "chicken-fill",
    name: "Chicken Fill",
    svg: `<i class="icon-chicken-fill"></i>`,
    jsx: '<i className="icon-chicken-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "chicken-line",
    name: "Chicken Line",
    svg: `<i class="icon-chicken-line"></i>`,
    jsx: '<i className="icon-chicken-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "chat-fill",
    name: "Chat Fill",
    svg: `<i class="icon-chat-fill"></i>`,
    jsx: '<i className="icon-chat-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "chat-line",
    name: "Chat Line",
    svg: `<i class="icon-chat-line"></i>`,
    jsx: '<i className="icon-chat-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "check-in-fill",
    name: "Check In Fill",
    svg: `<i class="icon-check-in-fill"></i>`,
    jsx: '<i className="icon-check-in-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "check-in-line",
    name: "Check In Line",
    svg: `<i class="icon-check-in-line"></i>`,
    jsx: '<i className="icon-check-in-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "check-out-fill",
    name: "Check Out Fill",
    svg: `<i class="icon-check-out-fill"></i>`,
    jsx: '<i className="icon-check-out-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "check-out-line",
    name: "Check Out Line",
    svg: `<i class="icon-check-out-line"></i>`,
    jsx: '<i className="icon-check-out-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "city-fill",
    name: "City Fill",
    svg: `<i class="icon-city-fill"></i>`,
    jsx: '<i className="icon-city-fill"></i>',
    category: "Misc",
  },
  {
    id: "city-line",
    name: "City Line",
    svg: `<i class="icon-city-line"></i>`,
    jsx: '<i className="icon-city-line"></i>',
    category: "Misc",
  },
  {
    id: "clock-fill",
    name: "Clock Fill",
    svg: `<i class="icon-clock-fill"></i>`,
    jsx: '<i className="icon-clock-fill"></i>',
    category: "Misc",
  },
  {
    id: "clock-line",
    name: "Clock Line",
    svg: `<i class="icon-clock-line"></i>`,
    jsx: '<i className="icon-clock-line"></i>',
    category: "Misc",
  },
  {
    id: "coffee-cup-fill",
    name: "Coffee Cup Fill",
    svg: `<i class="icon-coffee-cup-fill"></i>`,
    jsx: '<i className="icon-coffee-cup-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "coffee-cup-line",
    name: "Coffee Cup Line",
    svg: `<i class="icon-coffee-line"></i>`,
    jsx: '<i className="icon-coffee-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "coffee-machine-fill",
    name: "Coffee Machine Fill",
    svg: `<i class="icon-coffee-machine-fill"></i>`,
    jsx: '<i className="icon-coffee-machine-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "coffee-machine-line",
    name: "Coffee Machine Line",
    svg: `<i class="icon-coffee-machine-line"></i>`,
    jsx: '<i className="icon-coffee-machine-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "coking-pot-fill",
    name: "Coking Pot Fill",
    svg: `<i class="icon-coking-pot-fill"></i>`,
    jsx: '<i className="icon-coking-pot-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "coking-pot-line",
    name: "Coking Pot Line",
    svg: `<i class="icon-coking-pot-line"></i>`,
    jsx: '<i className="icon-coking-pot-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "conference-fill",
    name: "Conference Fill",
    svg: `<i class="icon-conference-fill\"></i>`,
    jsx: '<i className="icon-conference-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "conference-line",
    name: "Conference Line",
    svg: `<i class="icon-conference-line\"></i>`,
    jsx: '<i className="icon-conference-line"></i>',
    category: "Accommodation",
  },
  {
    id: "container-fill",
    name: "Container Fill",
    svg: `<i class="icon-container-fill"></i>`,
    jsx: '<i className="icon-container-fill"></i>',
    category: "Facilities",
  },
  {
    id: "container-line",
    name: "Container Line",
    svg: `<i class="icon-container-line"></i>`,
    jsx: '<i className="icon-container-line"></i>',
    category: "Facilities",
  },
  {
    id: "corridor-fill",
    name: "Corridor Fill",
    svg: `<i class="icon-corridor-fill\"></i>`,
    jsx: '<i className="icon-corridor-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "corridor-line",
    name: "Corridor Line",
    svg: `<i class="icon-corridor-line\"></i>`,
    jsx: '<i className="icon-corridor-line"></i>',
    category: "Accommodation",
  },
  {
    id: "court-fill",
    name: "Court Fill",
    svg: `<i class="icon-court-fill\"></i>`,
    jsx: '<i className="icon-court-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "court-line",
    name: "Court Line",
    svg: `<i class="icon-court-line\"></i>`,
    jsx: '<i className="icon-court-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "cpu-fill",
    name: "Cpu Fill",
    svg: `<i class="icon-cpu-fill\"></i>`,
    jsx: '<i className="icon-cpu-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "cpu-line",
    name: "Cpu Line",
    svg: `<i class="icon-cpu-line\"></i>`,
    jsx: '<i className="icon-cpu-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "cycle-fill",
    name: "Cycle Fill",
    svg: `<i class="icon-cycle-fill\"></i>`,
    jsx: '<i className="icon-cycle-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "cycle-line",
    name: "Cycle Line",
    svg: `<i class="icon-cycle-line\"></i>`,
    jsx: '<i className="icon-cycle-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "currency-fill",
    name: "Currency Fill",
    svg: `<i class="icon-currency-fill\"></i>`,
    jsx: '<i className="icon-currency-fill"></i>',
    category: "Finance",
  },
  {
    id: "currency-line",
    name: "Currency Line",
    svg: `<i class="icon-currency-line\"></i>`,
    jsx: '<i className="icon-currency-line"></i>',
    category: "Finance",
  },
  {
    id: "dart-fill",
    name: "Dart Fill",
    svg: `<i class="icon-dart-fill"></i>`,
    jsx: '<i className="icon-dart-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "dart-line",
    name: "Dart Line",
    svg: `<i class="icon-dart-line"></i>`,
    jsx: '<i className="icon-dart-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "data-port-fill",
    name: "Data Port Fill",
    svg: `<i class="icon-data-port-fill\"></i>`,
    jsx: '<i className="icon-data-port-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "data-port-line",
    name: "Data Port Line",
    svg: `<i class="icon-data-port-line\"></i>`,
    jsx: '<i className="icon-data-port-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "diet-fill",
    name: "Diet Fill",
    svg: `<i class="icon-diet-fill\"></i>`,
    jsx: '<i className="icon-diet-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "diet-line",
    name: "Diet Line",
    svg: `<i class="icon-diet-line\"></i>`,
    jsx: '<i className="icon-diet-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "disco-fill",
    name: "Disco Fill",
    svg: `<i class="icon-disco-fill\"></i>`,
    jsx: '<i className="icon-disco-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "disco-line",
    name: "Disco Line",
    svg: `<i class="icon-disco-line\"></i>`,
    jsx: '<i className="icon-disco-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "discount-fill",
    name: "Discount Fill",
    svg: `<i class="icon-discount-fill\"></i>`,
    jsx: '<i className="icon-discount-fill"></i>',
    category: "Finance",
  },
  {
    id: "discount-line",
    name: "Discount Line",
    svg: `<i class="icon-discount-line\"></i>`,
    jsx: '<i className="icon-discount-line"></i>',
    category: "Finance",
  },
  {
    id: "dish-fill",
    name: "Dish Fill",
    svg: `<i class="icon-dish-fill\"></i>`,
    jsx: '<i className="icon-dish-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "dish-line",
    name: "Dish Line",
    svg: `<i class="icon-dish-line\"></i>`,
    jsx: '<i className="icon-dish-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "dishwasher-fill",
    name: "Dishwasher Fill",
    svg: `<i class="icon-dishwasher-fill"></i>`,
    jsx: '<i className="icon-dishwasher-fill"></i>',
    category: "Facilities",
  },
  {
    id: "dishwasher-line",
    name: "Dishwasher Line",
    svg: `<i class="icon-dishwasher-line"></i>`,
    jsx: '<i className="icon-dishwasher-line"></i>',
    category: "Facilities",
  },
  {
    id: "dispencer-fill",
    name: "Dispencer Fill",
    svg: `<i class="icon-dispencer-fill"></i>`,
    jsx: '<i className="icon-dispencer-fill"></i>',
    category: "Facilities",
  },
  {
    id: "dispencer-line",
    name: "Dispencer Line",
    svg: `<i class="icon-dispencer-line"></i>`,
    jsx: '<i className="icon-dispencer-line"></i>',
    category: "Facilities",
  },
  {
    id: "door-fill",
    name: "Door Fill",
    svg: `<i class="icon-door-fill\"></i>`,
    jsx: '<i className="icon-door-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "door-line",
    name: "Door Line",
    svg: `<i class="icon-door-line\"></i>`,
    jsx: '<i className="icon-door-line"></i>',
    category: "Accommodation",
  },
  {
    id: "door-man-fill",
    name: "Door Man Fill",
    svg: `<i class="icon-door-man-fill\"></i>`,
    jsx: '<i className="icon-door-man-fill"></i>',
    category: "Services",
  },
  {
    id: "door-man-line",
    name: "Door Man Line",
    svg: `<i class="icon-door-man-line\"></i>`,
    jsx: '<i className="icon-door-man-line"></i>',
    category: "Services",
  },
  {
    id: "dress-fill",
    name: "Dress Fill",
    svg: `<i class="icon-dress-fill"></i>`,
    jsx: '<i className="icon-dress-fill"></i>',
    category: "Shopping",
  },
  {
    id: "dress-line",
    name: "Dress Line",
    svg: `<i class="icon-dress-line"></i>`,
    jsx: '<i className="icon-dress-line"></i>',
    category: "Shopping",
  },
  {
    id: "drop-fill",
    name: "Drop Fill",
    svg: `<i class="icon-drop-fill"></i>`,
    jsx: '<i className="icon-drop-fill"></i>',
    category: "Misc",
  },
  {
    id: "drop-line",
    name: "Drop Line",
    svg: `<i class="icon-drop-line"></i>`,
    jsx: '<i className="icon-drop-line"></i>',
    category: "Misc",
  },
  {
    id: "dry-clean-fill",
    name: "Dry Clean Fill",
    svg: `<i class="icon-dry-clean-fill\"></i>`,
    jsx: '<i className="icon-dry-clean-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "dry-clean-line",
    name: "Dry Clean Line",
    svg: `<i class="icon-dry-clean-line\"></i>`,
    jsx: '<i className="icon-dry-clean-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "dryer-fill",
    name: "Dryer Fill",
    svg: `<i class="icon-dryer-fill\"></i>`,
    jsx: '<i className="icon-dryer-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "dryer-line",
    name: "Dryer Line",
    svg: `<i class="icon-dryer-line\"></i>`,
    jsx: '<i className="icon-dryer-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "electric-outlet-fill",
    name: "Electric Outlet Fill",
    svg: `<i class="icon-electric-outlet-fill\"></i>`,
    jsx: '<i className="icon-electric-outlet-fill"></i>',
    category: "Facilities",
  },
  {
    id: "electric-outlet-line",
    name: "Electric Outlet Line",
    svg: `<i class="icon-electric-outlet-line\"></i>`,
    jsx: '<i className="icon-electric-outlet-line"></i>',
    category: "Facilities",
  },
  {
    id: "heart-fill",
    name: "Heart Fill",
    svg: `<i class="icon-heart-fill"></i>`,
    jsx: '<i className="icon-heart-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "heart-line",
    name: "Heart Line",
    svg: `<i class="icon-heart-line"></i>`,
    jsx: '<i className="icon-heart-line"></i>',
    category: "Health & Others",
  },
  {
    id: "fan-fill",
    name: "Fan Fill",
    svg: `<i class="icon-fan-fill"></i>`,
    jsx: '<i className="icon-fan-fill"></i>',
    category: "Facilities",
  },
  {
    id: "fan-line",
    name: "Fan Line",
    svg: `<i class="icon-fan-line"></i>`,
    jsx: '<i className="icon-fan-line"></i>',
    category: "Facilities",
  },
  {
    id: "fire-extinguisher-fill",
    name: "Fire Extinguisher Fill",
    svg: `<i class="icon-fire-extinguisher-fill\"></i>`,
    jsx: '<i className="icon-fire-extinguisher-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "fire-extinguisher-line",
    name: "Fire Extinguisher Line",
    svg: `<i class="icon-fire-extinguisher-line\"></i>`,
    jsx: '<i className="icon-fire-extinguisher-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "fish-fill",
    name: "Fish Fill",
    svg: `<i class="icon-fish-fill"></i>`,
    jsx: '<i className="icon-fish-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "fish-line",
    name: "Fish Line",
    svg: `<i class="icon-fish-line"></i>`,
    jsx: '<i className="icon-fish-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "fence-fill",
    name: "Fence Fill",
    svg: `<i class="icon-fence-fill\"></i>`,
    jsx: '<i className="icon-fence-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "fence-line",
    name: "Fence Line",
    svg: `<i class="icon-fence-line\"></i>`,
    jsx: '<i className="icon-fence-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "ferry-fill",
    name: "Ferry Fill",
    svg: `<i class="icon-ferry-fill"></i>`,
    jsx: '<i className="icon-ferry-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "ferry-line",
    name: "Ferry Line",
    svg: `<i class="icon-ferry-line"></i>`,
    jsx: '<i className="icon-ferry-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "flash-fill",
    name: "Flash Fill",
    svg: `<i class="icon-flash-fill"></i>`,
    jsx: '<i className="icon-flash-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "flash-line",
    name: "Flash Line",
    svg: `<i class="icon-flash-line"></i>`,
    jsx: '<i className="icon-flash-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "flower-fill",
    name: "Flower Fill",
    svg: `<i class="icon-flower-fill\"></i>`,
    jsx: '<i className="icon-flower-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "flower-line",
    name: "Flower Line",
    svg: `<i class="icon-flower-line\"></i>`,
    jsx: '<i className="icon-flower-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "mini-fridge-fill",
    name: "Mini Fridge Fill",
    svg: `<i class="icon-mini-fridge-fill"></i>`,
    jsx: '<i className="icon-mini-fridge-fill"></i>',
    category: "Facilities",
  },
  {
    id: "mini-fridge-line",
    name: "Mini Fridge Line",
    svg: `<i class="icon-mini-fridge-line"></i>`,
    jsx: '<i className="icon-mini-fridge-line"></i>',
    category: "Facilities",
  },
  {
    id: "front-office-fill",
    name: "Front Office Fill",
    svg: `<i class="icon-front-office-fill\"></i>`,
    jsx: '<i className="icon-front-office-fill"></i>',
    category: "Services",
  },
  {
    id: "front-office-line",
    name: "Front Office Line",
    svg: `<i class="icon-front-office-line\"></i>`,
    jsx: '<i className="icon-front-office-line"></i>',
    category: "Services",
  },
  {
    id: "fruit-fill",
    name: "Fruit Fill",
    svg: `<i class="icon-fruit-fill"></i>`,
    jsx: '<i className="icon-fruit-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "fruit-line",
    name: "Fruit Line",
    svg: `<i class="icon-fruit-line"></i>`,
    jsx: '<i className="icon-fruit-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "game-fill",
    name: "Game Fill",
    svg: `<i class="icon-game-fill\"></i>`,
    jsx: '<i className="icon-game-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "game-line",
    name: "Game Line",
    svg: `<i class="icon-game-line\"></i>`,
    jsx: '<i className="icon-game-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "gas-station-fill",
    name: "Gas Station Fill",
    svg: `<i class="icon-gas-station-fill\"></i>`,
    jsx: '<i className="icon-gas-station-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "gas-station-line",
    name: "Gas Station Line",
    svg: `<i class="icon-gas-station-line\"></i>`,
    jsx: '<i className="icon-gas-station-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "gender-female-fill",
    name: "Gender Female Fill",
    svg: `<i class="icon-gender-female-fill\"></i>`,
    jsx: '<i className="icon-gender-female-fill"></i>',
    category: "Misc",
  },
  {
    id: "gender-female-line",
    name: "Gender Female Line",
    svg: `<i class="icon-gender-female-line\"></i>`,
    jsx: '<i className="icon-gender-female-line"></i>',
    category: "Misc",
  },
  {
    id: "gift-fill",
    name: "Gift Fill",
    svg: `<i class="icon-gift-fill\"></i>`,
    jsx: '<i className="icon-gift-fill"></i>',
    category: "Misc",
  },
  {
    id: "gift-line",
    name: "Gift Line",
    svg: `<i class="icon-gift-line\"></i>`,
    jsx: '<i className="icon-gift-line"></i>',
    category: "Misc",
  },
  {
    id: "golf-fill",
    name: "Golf Fill",
    svg: `<i class="icon-golf-fill\"></i>`,
    jsx: '<i className="icon-golf-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "golf-line",
    name: "Golf Line",
    svg: `<i class="icon-golf-line\"></i>`,
    jsx: '<i className="icon-golf-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "glove-fill",
    name: "Glove Fill",
    svg: `<i class="icon-glove-fill"></i>`,
    jsx: '<i className="icon-glove-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "glove-line",
    name: "Glove Line",
    svg: `<i class="icon-glove-line"></i>`,
    jsx: '<i className="icon-glove-line"></i>',
    category: "Health & Others",
  },
  {
    id: "grill-fill",
    name: "Grill Fill",
    svg: `<i class="icon-grill-fill\"></i>`,
    jsx: '<i className="icon-grill-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "grill-line",
    name: "Grill Line",
    svg: `<i class="icon-grill-line\"></i>`,
    jsx: '<i className="icon-grill-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "group-fill",
    name: "Group Fill",
    svg: `<i class="icon-group-fill\"></i>`,
    jsx: '<i className="icon-group-fill"></i>',
    category: "Misc",
  },
  {
    id: "group-line",
    name: "Group Line",
    svg: `<i class="icon-group-line\"></i>`,
    jsx: '<i className="icon-group-line"></i>',
    category: "Misc",
  },
  {
    id: "guitar-fill",
    name: "Guitar Fill",
    svg: `<i class="icon-guitar-fill\"></i>`,
    jsx: '<i className="icon-guitar-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "guitar-line",
    name: "Guitar Line",
    svg: `<i class="icon-guitar-line\"></i>`,
    jsx: '<i className="icon-guitar-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "gym-fill",
    name: "Gym Fill",
    svg: `<i class="icon-gym-fill\"></i>`,
    jsx: '<i className="icon-gym-fill"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "gym-line",
    name: "Gym Line",
    svg: `<i class="icon-gym-line\"></i>`,
    jsx: '<i className="icon-gym-line"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "hand-shake-fill",
    name: "Hand Shake Fill",
    svg: `<i class="icon-hand-shake-fill\"></i>`,
    jsx: '<i className="icon-hand-shake-fill"></i>',
    category: "Misc",
  },
  {
    id: "hand-shake-line",
    name: "Hand Shake Line",
    svg: `<i class="icon-hand-shake-line\"></i>`,
    jsx: '<i className="icon-hand-shake-line"></i>',
    category: "Misc",
  },
  {
    id: "heater-fill",
    name: "Heater Fill",
    svg: `<i class="icon-heater-fill"></i>`,
    jsx: '<i className="icon-heater-fill"></i>',
    category: "Facilities",
  },
  {
    id: "heater-line",
    name: "Heater Line",
    svg: `<i class="icon-heater-line"></i>`,
    jsx: '<i className="icon-heater-line"></i>',
    category: "Facilities",
  },
  {
    id: "helicopter-fill",
    name: "Helicopter Fill",
    svg: `<i class="icon-helicopter-fill"></i>`,
    jsx: '<i className="icon-helicopter-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "helicopter-line",
    name: "Helicopter Line",
    svg: `<i class="icon-helicopter-line"></i>`,
    jsx: '<i className="icon-helicopter-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "home-fill",
    name: "Home Fill",
    svg: `<i class="icon-home-fill"></i>`,
    jsx: '<i className="icon-home-fill"></i>',
    category: "Facilities",
  },
  {
    id: "home-line",
    name: "Home Line",
    svg: `<i class="icon-home-line"></i>`,
    jsx: '<i className="icon-home-line"></i>',
    category: "Facilities",
  },
  {
    id: "horse-fill",
    name: "Horse Fill",
    svg: `<i class="icon-horse-fill\"></i>`,
    jsx: '<i className="icon-horse-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "horse-line",
    name: "Horse Line",
    svg: `<i class="icon-horse-line\"></i>`,
    jsx: '<i className="icon-horse-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "hour-glass-fill",
    name: "Hour Glass Fill",
    svg: `<i class="icon-hour-glass-fill\"></i>`,
    jsx: '<i className="icon-hour-glass-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "hour-glass-line",
    name: "Hour Glass Line",
    svg: `<i class="icon-hour-glass-line\"></i>`,
    jsx: '<i className="icon-hour-glass-line"></i>',
    category: "Health & Others",
  },
  {
    id: "hotspot-fill",
    name: "Hotspot Fill",
    svg: `<i class="icon-hotspot-fill\"></i>`,
    jsx: '<i className="icon-hotspot-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "hotspot-line",
    name: "Hotspot Line",
    svg: `<i class="icon-hotspot-line\"></i>`,
    jsx: '<i className="icon-hotspot-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "intercom-fill",
    name: "Intercom Fill",
    svg: `<i class="icon-intercom-fill"></i>`,
    jsx: '<i className="icon-intercom-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "intercom-line",
    name: "Intercom Line",
    svg: `<i class="icon-intercom-line"></i>`,
    jsx: '<i className="icon-intercom-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "internet-fill",
    name: "Internet Fill",
    svg: `<i class="icon-internet-fill\"></i>`,
    jsx: '<i className="icon-internet-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "internet-line",
    name: "Internet Line",
    svg: `<i class="icon-internet-line\"></i>`,
    jsx: '<i className="icon-internet-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "ironing-board-fill",
    name: "Ironing Board Fill",
    svg: `<i class="icon-ironing-board-fill\"></i>`,
    jsx: '<i className="icon-ironing-board-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "ironing-board-line",
    name: "Ironing Board Line",
    svg: `<i class="icon-ironing-board-line\"></i>`,
    jsx: '<i className="icon-ironing-board-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "jacuzzi-fill",
    name: "Jacuzzi Fill",
    svg: `<i class="icon-jacuzzi-fill\"></i>`,
    jsx: '<i className="icon-jacuzzi-fill"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "jacuzzi-line",
    name: "Jacuzzi Line",
    svg: `<i class="icon-jacuzzi-line\"></i>`,
    jsx: '<i className="icon-jacuzzi-line"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "kettle-fill",
    name: "Kettle Fill",
    svg: `<i class="icon-kettle-fill"></i>`,
    jsx: '<i className="icon-kettle-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "kettle-line",
    name: "Kettle Line",
    svg: `<i class="icon-kettle-line"></i>`,
    jsx: '<i className="icon-kettle-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "keycard-fill",
    name: "Keycard Fill",
    svg: `<i class="icon-keycard-fill"></i>`,
    jsx: '<i className="icon-keycard-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "keycard-line",
    name: "Keycard Line",
    svg: `<i class="icon-keycard-line"></i>`,
    jsx: '<i className="icon-keycard-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "key-fill",
    name: "Key Fill",
    svg: `<i class="icon-key-fill"></i>`,
    jsx: '<i className="icon-key-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "key-line",
    name: "Key Line",
    svg: `<i class="icon-key-line"></i>`,
    jsx: '<i className="icon-key-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "knife-fork-fill",
    name: "Knife Fork Fill",
    svg: `<i class="icon-knife-fork-fill\"></i>`,
    jsx: '<i className="icon-knife-fork-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "knife-fork-line",
    name: "Knife Fork Line",
    svg: `<i class="icon-knife-fork-line\"></i>`,
    jsx: '<i className="icon-knife-fork-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "language-fill",
    name: "Language Fill",
    svg: `<i class="icon-langauge-fill\"></i>`,
    jsx: '<i className="icon-langauge-fill"></i>',
    category: "Misc",
  },
  {
    id: "language-line",
    name: "Language Line",
    svg: `<i class="icon-langauge-line\"></i>`,
    jsx: '<i className="icon-langauge-line"></i>',
    category: "Misc",
  },
  {
    id: "laptop-fill",
    name: "Laptop Fill",
    svg: `<i class="icon-laptop-fill"></i>`,
    jsx: '<i className="icon-laptop-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "laptop-line",
    name: "Laptop Line",
    svg: `<i class="icon-laptop-line"></i>`,
    jsx: '<i className="icon-laptop-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "lift-fill",
    name: "Lift Fill",
    svg: `<i class="icon-lift-fill\"></i>`,
    jsx: '<i className="icon-lift-fill"></i>',
    category: "Facilities",
  },
  {
    id: "lift-line",
    name: "Lift Line",
    svg: `<i class="icon-lift-line\"></i>`,
    jsx: '<i className="icon-lift-line"></i>',
    category: "Facilities",
  },
  {
    id: "liquor-fill",
    name: "Liquor Fill",
    svg: `<i class="icon-liquor-fill\"></i>`,
    jsx: '<i className="icon-liquor-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "liquor-line",
    name: "Liquor Line",
    svg: `<i class="icon-liquor-line\"></i>`,
    jsx: '<i className="icon-liquor-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "lock-fill",
    name: "Lock Fill",
    svg: `<i class="icon-lock-fill"></i>`,
    jsx: '<i className="icon-lock-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "lock-line",
    name: "Lock Line",
    svg: `<i class="icon-lock-line"></i>`,
    jsx: '<i className="icon-lock-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "luggage-fill",
    name: "Luggage Fill",
    svg: `<i class="icon-luggage-fill\"></i>`,
    jsx: '<i className="icon-luggage-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "luggage-line",
    name: "Luggage Line",
    svg: `<i class="icon-luggage-line\"></i>`,
    jsx: '<i className="icon-luggage-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "mask-fill",
    name: "Mask Fill",
    svg: `<i class="icon-mask-fill"></i>`,
    jsx: '<i className="icon-mask-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "mask-line",
    name: "Mask Line",
    svg: `<i class="icon-mask-line"></i>`,
    jsx: '<i className="icon-mask-line"></i>',
    category: "Health & Others",
  },
  {
    id: "medical-fill",
    name: "Medical Fill",
    svg: `<i class="icon-medical-fill\"></i>`,
    jsx: '<i className="icon-medical-fill"></i>',
    category: "Medical & Safety",
  },
  {
    id: "medical-line",
    name: "Medical Line",
    svg: `<i class="icon-medical-line\"></i>`,
    jsx: '<i className="icon-medical-line"></i>',
    category: "Medical & Safety",
  },
  {
    id: "menu-fill",
    name: "Menu Fill",
    svg: `<i class="icon-menu-fill\"></i>`,
    jsx: '<i className="icon-menu-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "menu-line",
    name: "Menu Line",
    svg: `<i class="icon-menu-line\"></i>`,
    jsx: '<i className="icon-menu-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "milk-fill",
    name: "Milk Fill",
    svg: `<i class="icon-milk-fill"></i>`,
    jsx: '<i className="icon-milk-fill"></i>',
    category: "Food & Beverages",
  },
  {
    id: "milk-line",
    name: "Milk Line",
    svg: `<i class="icon-milk-line"></i>`,
    jsx: '<i className="icon-milk-line"></i>',
    category: "Food & Beverages",
  },
  {
    id: "mirror-fill",
    name: "Mirror Fill",
    svg: `<i class="icon-mirror-fill"></i>`,
    jsx: '<i className="icon-mirror-fill"></i>',
    category: "Facilities",
  },
  {
    id: "mirror-line",
    name: "Mirror Line",
    svg: `<i class="icon-mirror-line"></i>`,
    jsx: '<i className="icon-mirror-line"></i>',
    category: "Facilities",
  },
  {
    id: "mountain-fill",
    name: "Mountain Fill",
    svg: `<i class="icon-mountain-fill"></i>`,
    jsx: '<i className="icon-mountain-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "mountain-line",
    name: "Mountain Line",
    svg: `<i class="icon-mountain-line"></i>`,
    jsx: '<i className="icon-mountain-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "network-fill",
    name: "Network Fill",
    svg: `<i class="icon-network-fill"></i>`,
    jsx: '<i className="icon-network-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "network-line",
    name: "Network Line",
    svg: `<i class="icon-network-line"></i>`,
    jsx: '<i className="icon-network-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "newspaper-fill",
    name: "Newspaper Fill",
    svg: `<i class="icon-newspaper-fill\"></i>`,
    jsx: '<i className="icon-newspaper-fill"></i>',
    category: "Misc",
  },
  {
    id: "newspaper-line",
    name: "Newspaper Line",
    svg: `<i class="icon-newspaper-line\"></i>`,
    jsx: '<i className="icon-newspaper-line"></i>',
    category: "Misc",
  },
  {
    id: "no-parking-fill",
    name: "No Parking Fill",
    svg: `<i class="icon-no-parking-fill"></i>`,
    jsx: '<i className="icon-no-parking-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "no-parking-line",
    name: "No Parking Line",
    svg: `<i class="icon-no-parking-line"></i>`,
    jsx: '<i className="icon-no-parking-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "no-smoking-fill",
    name: "No Smoking Fill",
    svg: `<i class="icon-no-smokin-fill\"></i>`,
    jsx: '<i className="icon-no-smokin-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "no-smoking-line",
    name: "No Smoking Line",
    svg: `<i class="icon-no-smoking-line\"></i>`,
    jsx: '<i className="icon-no-smoking-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "ott-fill",
    name: "OTT Fill",
    svg: `<i class="icon-ott-fill"></i>`,
    jsx: '<i className="icon-ott-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "ott-line",
    name: "OTT Line",
    svg: `<i class="icon-ott-line"></i>`,
    jsx: '<i className="icon-ott-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "oven-fill",
    name: "Oven Fill",
    svg: `<i class="icon-oven-fill"></i>`,
    jsx: '<i className="icon-oven-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "oven-line",
    name: "Oven Line",
    svg: `<i class="icon-oven-line"></i>`,
    jsx: '<i className="icon-oven-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "toilet-paper-fill",
    name: "Toilet Paper Fill",
    svg: `<i class="icon-toilet-paper-fill"></i>`,
    jsx: '<i className="icon-toilet-paper-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "toilet-paper-line",
    name: "Toilet Paper Line",
    svg: `<i class="icon-toilet-paper-line"></i>`,
    jsx: '<i className="icon-toilet-paper-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "twin-bed-fill",
    name: "Twin Bed Fill",
    svg: `<i class="icon-twin-bed-fill"></i>`,
    jsx: '<i className="icon-twin-bed-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "twin-bed-line",
    name: "Twin Bed Line",
    svg: `<i class="icon-twin-bed-line"></i>`,
    jsx: '<i className="icon-twin-bed-line"></i>',
    category: "Accommodation",
  },
  {
    id: "parking-fill",
    name: "Parking Fill",
    svg: `<i class="icon-parking-fill\"></i>`,
    jsx: '<i className="icon-parking-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "parking-line",
    name: "Parking Line",
    svg: `<i class="icon-parking-line\"></i>`,
    jsx: '<i className="icon-parking-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "park-fill",
    name: "Park Fill",
    svg: `<i class="icon-park-fill\"></i>`,
    jsx: '<i className="icon-park-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "park-line",
    name: "Park Line",
    svg: `<i class="icon-park-line\"></i>`,
    jsx: '<i className="icon-park-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "pet-fill",
    name: "Pet Fill",
    svg: `<i class="icon-pet-fill\"></i>`,
    jsx: '<i className="icon-pet-fill"></i>',
    category: "Misc",
  },
  {
    id: "pet-line",
    name: "Pet Line",
    svg: `<i class="icon-pet-line\"></i>`,
    jsx: '<i className="icon-pet-line"></i>',
    category: "Misc",
  },
  {
    id: "phone-fill",
    name: "Phone Fill",
    svg: `<i class="icon-phone-fill\"></i>`,
    jsx: '<i className="icon-phone-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "phone-line",
    name: "Phone Line",
    svg: `<i class="icon-phone-line\"></i>`,
    jsx: '<i className="icon-phone-line"></i>',
    category: "Health & Others",
  },
  {
    id: "piano-fill",
    name: "Piano Fill",
    svg: `<i class="icon-piano-fill"></i>`,
    jsx: '<i className="icon-piano-fill"></i>',
    category: "Music & Entertainment",
  },
  {
    id: "piano-line",
    name: "Piano Line",
    svg: `<i class="icon-piano-line"></i>`,
    jsx: '<i className="icon-piano-line"></i>',
    category: "Music & Entertainment",
  },
  {
    id: "pillow-fill",
    name: "Pillow Fill",
    svg: `<i class="icon-pillow-fill"></i>`,
    jsx: '<i className="icon-pillow-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "pillow-line",
    name: "Pillow Line",
    svg: `<i class="icon-pillow-line"></i>`,
    jsx: '<i className="icon-pillow-line"></i>',
    category: "Accommodation",
  },
  {
    id: "plug-fill",
    name: "Plug Fill",
    svg: `<i class="icon-plug-fill\"></i>`,
    jsx: '<i className="icon-plug-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "plug-line",
    name: "Plug Line",
    svg: `<i class="icon-plug-line\"></i>`,
    jsx: '<i className="icon-plug-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "pot-fill",
    name: "Pot Fill",
    svg: `<i class="icon-pot-fill"></i>`,
    jsx: '<i className="icon-pot-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "pot-line",
    name: "Pot Line",
    svg: `<i class="icon-pot-line"></i>`,
    jsx: '<i className="icon-pot-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "pray-fill",
    name: "Pray Fill",
    svg: `<i class="icon-pray-fill"></i>`,
    jsx: '<i className="icon-pray-fill"></i>',
    category: "Misc",
  },
  {
    id: "pray-line",
    name: "Pray Line",
    svg: `<i class="icon-pray-line"></i>`,
    jsx: '<i className="icon-pray-line"></i>',
    category: "Misc",
  },
  {
    id: "presentation-fill",
    name: "Presentation Fill",
    svg: `<i class="icon-presentation-fill\"></i>`,
    jsx: '<i className="icon-presentation-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "presentation-line",
    name: "Presentation Line",
    svg: `<i class="icon-presentation-line\"></i>`,
    jsx: '<i className="icon-presentation-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "printer-fill",
    name: "Printer Fill",
    svg: `<i class="icon-printer-fill\"></i>`,
    jsx: '<i className="icon-printer-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "printer-line",
    name: "Printer Line",
    svg: `<i class="icon-printer-line\"></i>`,
    jsx: '<i className="icon-printer-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "puzzle-fill",
    name: "Puzzle Fill",
    svg: `<i class="icon-puzzle-fill"></i>`,
    jsx: '<i className="icon-puzzle-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "puzzle-line",
    name: "Puzzle Line",
    svg: `<i class="icon-puzzle-line"></i>`,
    jsx: '<i className="icon-puzzle-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "qr-fill",
    name: "QR Fill",
    svg: `<i class="icon-qr-fill"></i>`,
    jsx: '<i className="icon-qr-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "qr-line",
    name: "QR Line",
    svg: `<i class="icon-qr-line"></i>`,
    jsx: '<i className="icon-qr-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "recreational-vehicle-fill",
    name: "Recreational Vehicle Fill",
    svg: `<i class="icon-recreational-vehicle-fill\"></i>`,
    jsx: '<i className="icon-recreational-vehicle-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "recreational-vehicle-line",
    name: "Recreational Vehicle Line",
    svg: `<i class="icon-recreational-vehicle-line\"></i>`,
    jsx: '<i className="icon-recreational-vehicle-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "sauna-fill",
    name: "Sauna Fill",
    svg: `<i class="icon-sauna-fill\"></i>`,
    jsx: '<i className="icon-sauna-fill"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "sauna-line",
    name: "Sauna Line",
    svg: `<i class="icon-sauna-line\"></i>`,
    jsx: '<i className="icon-sauna-line"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "scissor-fill",
    name: "Scissor Fill",
    svg: `<i class="icon-scissor-fill\"></i>`,
    jsx: '<i className="icon-scissor-fill"></i>',
    category: "Misc",
  },
  {
    id: "scissor-line",
    name: "Scissor Line",
    svg: `<i class="icon-scissor-line\"></i>`,
    jsx: '<i className="icon-scissor-line"></i>',
    category: "Misc",
  },
  {
    id: "scrub-fill",
    name: "Scrub Fill",
    svg: `<i class="icon-scrub-fill\"></i>`,
    jsx: '<i className="icon-scrub-fill"></i>',
    category: "Misc",
  },
  {
    id: "scrub-line",
    name: "Scrub Line",
    svg: `<i class="icon-scrub-line\"></i>`,
    jsx: '<i className="icon-scrub-line"></i>',
    category: "Misc",
  },
  {
    id: "security-fill",
    name: "Security Fill",
    svg: `<i class="icon-security-fill\"></i>`,
    jsx: '<i className="icon-security-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "security-line",
    name: "Security Line",
    svg: `<i class="icon-security-line\"></i>`,
    jsx: '<i className="icon-security-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "sewing-kit-fill",
    name: "Sewing Kit Fill",
    svg: `<i class="icon-sewing-kit-fill"></i>`,
    jsx: '<i className="icon-sewing-kit-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "sewing-kit-line",
    name: "Sewing Kit Line",
    svg: `<i class="icon-sewing-kit-line"></i>`,
    jsx: '<i className="icon-sewing-kit-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "shield-check-fill",
    name: "Shield Check Fill",
    svg: `<i class="icon-shield-check-fill\"></i>`,
    jsx: '<i className="icon-shield-check-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "shield-check-line",
    name: "Shield Check Line",
    svg: `<i class="icon-shield-check-line\"></i>`,
    jsx: '<i className="icon-shield-check-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "shoe-fill",
    name: "Shoe Fill",
    svg: `<i class="icon-shoe-fill\"></i>`,
    jsx: '<i className="icon-shoe-fill"></i>',
    category: "Shopping",
  },
  {
    id: "shoe-line",
    name: "Shoe Line",
    svg: `<i class="icon-shoe-line\"></i>`,
    jsx: '<i className="icon-shoe-line"></i>',
    category: "Shopping",
  },
  {
    id: "shop-fill",
    name: "Shop Fill",
    svg: `<i class="icon-shop-fill\"></i>`,
    jsx: '<i className="icon-shop-fill"></i>',
    category: "Shopping",
  },
  {
    id: "shop-line",
    name: "Shop Line",
    svg: `<i class="icon-shop-line\"></i>`,
    jsx: '<i className="icon-shop-line"></i>',
    category: "Shopping",
  },
  {
    id: "shopping-bag-fill",
    name: "Shopping Bag Fill",
    svg: `<i class="icon-shopping-bag-fill\"></i>`,
    jsx: '<i className="icon-shopping-bag-fill"></i>',
    category: "Shopping",
  },
  {
    id: "shopping-bag-line",
    name: "Shopping Bag Line",
    svg: `<i class="icon-shopping-bag-line\"></i>`,
    jsx: '<i className="icon-shopping-bag-line"></i>',
    category: "Shopping",
  },
  {
    id: "shower-fill",
    name: "Shower Fill",
    svg: `<i class="icon-shower-fill"></i>`,
    jsx: '<i className="icon-shower-fill"></i>',
    category: "Facilities",
  },
  {
    id: "shower-line",
    name: "Shower Line",
    svg: `<i class="icon-shower-line"></i>`,
    jsx: '<i className="icon-shower-line"></i>',
    category: "Facilities",
  },
  {
    id: "single-bed-fill",
    name: "Single Bed Fill",
    svg: `<i class="icon-single-bed-fill"></i>`,
    jsx: '<i className="icon-single-bed-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "single-bed-line",
    name: "Single Bed Line",
    svg: `<i class="icon-single-bed-line"></i>`,
    jsx: '<i className="icon-single-bed-line"></i>',
    category: "Accommodation",
  },
  {
    id: "skiing-fill",
    name: "Skiing Fill",
    svg: `<i class="icon-skiing-fill"></i>`,
    jsx: '<i className="icon-skiing-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "skiing-line",
    name: "Skiing Line",
    svg: `<i class="icon-skiing-line"></i>`,
    jsx: '<i className="icon-skiing-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "slipper-fill",
    name: "Slipper Fill",
    svg: `<i class="icon-slipper-fill"></i>`,
    jsx: '<i className="icon-slipper-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "slipper-line",
    name: "Slipper Line",
    svg: `<i class="icon-slipper-line"></i>`,
    jsx: '<i className="icon-slipper-line"></i>',
    category: "Accommodation",
  },
  {
    id: "smoking-fill",
    name: "Smoking Fill",
    svg: `<i class="icon-smoking-fill\"></i>`,
    jsx: '<i className="icon-smoking-fill"></i>',
    category: "Misc",
  },
  {
    id: "smoking-line",
    name: "Smoking Line",
    svg: `<i class="icon-smoking-line\"></i>`,
    jsx: '<i className="icon-smoking-line"></i>',
    category: "Misc",
  },
  {
    id: "snow-flake-fill",
    name: "Snow Flake Fill",
    svg: `<i class="icon-snow-flake-fill\"></i>`,
    jsx: '<i className="icon-snow-flake-fill"></i>',
    category: "Outdoor Condition",
  },
  {
    id: "snow-flake-line",
    name: "Snow Flake Line",
    svg: `<i class="icon-snow-flake-line\"></i>`,
    jsx: '<i className="icon-snow-flake-line"></i>',
    category: "Outdoor Condition",
  },
  {
    id: "sofa-fill",
    name: "Sofa Fill",
    svg: `<i class="icon-sofa-fill\"></i>`,
    jsx: '<i className="icon-sofa-fill"></i>',
    category: "Facilities",
  },
  {
    id: "sofa-line",
    name: "Sofa Line",
    svg: `<i class="icon-sofa-line\"></i>`,
    jsx: '<i className="icon-sofa-line"></i>',
    category: "Facilities",
  },
  {
    id: "sofa-2-fill",
    name: "Sofa 2 Fill",
    svg: `<i class="icon-sofa-2-fill"></i>`,
    jsx: '<i className="icon-sofa-2-fill"></i>',
    category: "Facilities",
  },
  {
    id: "sofa-2-line",
    name: "Sofa 2 Line",
    svg: `<i class="icon-sofa-2-line"></i>`,
    jsx: '<i className="icon-sofa-2-line"></i>',
    category: "Facilities",
  },
  {
    id: "sofa-set-fill",
    name: "Sofa Set Fill",
    svg: `<i class="icon-sofa-set-fill\"></i>`,
    jsx: '<i className="icon-sofa-set-fill"></i>',
    category: "Facilities",
  },
  {
    id: "sofa-set-line",
    name: "Sofa Set Line",
    svg: `<i class="icon-sofa-set-line\"></i>`,
    jsx: '<i className="icon-sofa-set-line"></i>',
    category: "Facilities",
  },
  {
    id: "solarium-fill",
    name: "Solarium Fill",
    svg: `<i class="icon-solarium-fill\"></i>`,
    jsx: '<i className="icon-solarium-fill"></i>',
    category: "Misc",
  },
  {
    id: "solarium-line",
    name: "Solarium Line",
    svg: `<i class="icon-solarium-line\"></i>`,
    jsx: '<i className="icon-solarium-line"></i>',
    category: "Misc",
  },
  {
    id: "spark-fill",
    name: "Spark Fill",
    svg: `<i class="icon-spark-fill\"></i>`,
    jsx: '<i className="icon-spark-fill"></i>',
    category: "Misc",
  },
  {
    id: "spark-line",
    name: "Spark Line",
    svg: `<i class="icon-spark-line\"></i>`,
    jsx: '<i className="icon-spark-line"></i>',
    category: "Misc",
  },
  {
    id: "speaker-fill",
    name: "Speaker Fill",
    svg: `<i class="icon-speaker-fill\"></i>`,
    jsx: '<i className="icon-speaker-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "speaker-line",
    name: "Speaker Line",
    svg: `<i class="icon-speaker-line\"></i>`,
    jsx: '<i className="icon-speaker-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "spray-fill",
    name: "Spray Fill",
    svg: `<i class="icon-spray-fill\"></i>`,
    jsx: '<i className="icon-spray-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "spray-line",
    name: "Spray Line",
    svg: `<i class="icon-spray-line\"></i>`,
    jsx: '<i className="icon-spray-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "stairs-fill",
    name: "Stairs Fill",
    svg: `<i class="icon-stairs-fill\"></i>`,
    jsx: '<i className="icon-stairs-fill"></i>',
    category: "Misc",
  },
  {
    id: "stairs-line",
    name: "Stairs Line",
    svg: `<i class="icon-stairs-line\"></i>`,
    jsx: '<i className="icon-stairs-line"></i>',
    category: "Misc",
  },
  {
    id: "storage-fill",
    name: "Storage Fill",
    svg: `<i class="icon-storage-fill\"></i>`,
    jsx: '<i className="icon-storage-fill"></i>',
    category: "Facilities",
  },
  {
    id: "storage-line",
    name: "Storage Line",
    svg: `<i class="icon-storage-line\"></i>`,
    jsx: '<i className="icon-storage-line"></i>',
    category: "Facilities",
  },
  {
    id: "sun-set-fill",
    name: "Sun Set Fill",
    svg: `<i class="icon-sun-set-fill\"></i>`,
    jsx: '<i className="icon-sun-set-fill"></i>',
    category: "Outdoor Condition",
  },
  {
    id: "sun-set-line",
    name: "Sun Set Line",
    svg: `<i class="icon-sun-set-line\"></i>`,
    jsx: '<i className="icon-sun-set-line"></i>',
    category: "Outdoor Condition",
  },
  {
    id: "support-fill",
    name: "Support Fill",
    svg: `<i class="icon-support-fill\"></i>`,
    jsx: '<i className="icon-support-fill"></i>',
    category: "Services",
  },
  {
    id: "support-line",
    name: "Support Line",
    svg: `<i class="icon-support-line\"></i>`,
    jsx: '<i className="icon-support-line"></i>',
    category: "Services",
  },
  {
    id: "swimming-fill",
    name: "Swimming Fill",
    svg: `<i class="icon-swimming-fill\"></i>`,
    jsx: '<i className="icon-swimming-fill"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "swimming-line",
    name: "Swimming Line",
    svg: `<i class="icon-swimming-line\"></i>`,
    jsx: '<i className="icon-swimming-line"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "swimming-pool-fill",
    name: "Swimming Pool Fill",
    svg: `<i class="icon-swimming-pool-fill\"></i>`,
    jsx: '<i className="icon-swimming-pool-fill"></i>',
    category: "Leisure & Amenities",
  },
  {
    id: "swimming-pool-line",
    name: "Swimming Pool Line",
    svg: `<i class="icon-swimming-pool-line\"></i>`,
    jsx: '<i className="icon-swimming-pool-line"></i>',
    category: "Leisure & Amenities",
  },
  {
    id: "table-tennis-fill",
    name: "Table Tennis Fill",
    svg: `<i class="icon-table-tennis-fill"></i>`,
    jsx: '<i className="icon-table-tennis-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "table-tennis-line",
    name: "Table Tennis Line",
    svg: `<i class="icon-table-tennis-line"></i>`,
    jsx: '<i className="icon-table-tennis-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "tapas-fill",
    name: "Tapas Fill",
    svg: `<i class="icon-tapas-fill"></i>`,
    jsx: '<i className="icon-tapas-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "tapas-line",
    name: "Tapas Line",
    svg: `<i class="icon-tapas-line"></i>`,
    jsx: '<i className="icon-tapas-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "target-fill",
    name: "Target Fill",
    svg: `<i class="icon-target-fill"></i>`,
    jsx: '<i className="icon-target-fill"></i>',
    category: "Misc",
  },
  {
    id: "target-line",
    name: "Target Line",
    svg: `<i class="icon-target-line"></i>`,
    jsx: '<i className="icon-target-line"></i>',
    category: "Misc",
  },
  {
    id: "telescope-fill",
    name: "Telescope Fill",
    svg: `<i class="icon-telescope-fill"></i>`,
    jsx: '<i className="icon-telescope-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "telescope-line",
    name: "Telescope Line",
    svg: `<i class="icon-telescope-line"></i>`,
    jsx: '<i className="icon-telescope-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "terrace-fill",
    name: "Terrace Fill",
    svg: `<i class="icon-terrace-fill"></i>`,
    jsx: '<i className="icon-terrace-fill"></i>',
    category: "Facilities",
  },
  {
    id: "terrace-line",
    name: "Terrace Line",
    svg: `<i class="icon-terrace-line"></i>`,
    jsx: '<i className="icon-terrace-line"></i>',
    category: "Facilities",
  },
  {
    id: "thermometer-fill",
    name: "Thermometer Fill",
    svg: `<i class="icon-thermometer-fill"></i>`,
    jsx: '<i className="icon-thermometer-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "thermometer-line",
    name: "Thermometer Line",
    svg: `<i class="icon-thermometer-line"></i>`,
    jsx: '<i className="icon-thermometer-line"></i>',
    category: "Health & Others",
  },
  {
    id: "ticket-fill",
    name: "Ticket Fill",
    svg: `<i class="icon-ticket-fill"></i>`,
    jsx: '<i className="icon-ticket-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "ticket-line",
    name: "Ticket Line",
    svg: `<i class="icon-ticket-line"></i>`,
    jsx: '<i className="icon-ticket-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "tooth-fill",
    name: "Tooth Fill",
    svg: `<i class="icon-tooth-fill"></i>`,
    jsx: '<i className="icon-tooth-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "tooth-line",
    name: "Tooth Line",
    svg: `<i class="icon-tooth-line"></i>`,
    jsx: '<i className="icon-tooth-line"></i>',
    category: "Health & Others",
  },
  {
    id: "tshirt-fill",
    name: "Tshirt Fill",
    svg: `<i class="icon-tshirt-fill"></i>`,
    jsx: '<i className="icon-tshirt-fill"></i>',
    category: "Shopping",
  },
  {
    id: "tshirt-line",
    name: "Tshirt Line",
    svg: `<i class="icon-tshirt-line"></i>`,
    jsx: '<i className="icon-tshirt-line"></i>',
    category: "Shopping",
  },
  {
    id: "towels-fill",
    name: "Towels Fill",
    svg: `<i class="icon-towels-fill\"></i>`,
    jsx: '<i className="icon-towels-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "towels-line",
    name: "Towels Line",
    svg: `<i class="icon-towels-line\"></i>`,
    jsx: '<i className="icon-towels-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "toilet-fill",
    name: "Toilet Fill",
    svg: `<i class="icon-toilet-fill\"></i>`,
    jsx: '<i className="icon-toilet-fill"></i>',
    category: "Misc",
  },
  {
    id: "toilet-line",
    name: "Toilet Line",
    svg: `<i class="icon-toilet-line\"></i>`,
    jsx: '<i className="icon-toilet-line"></i>',
    category: "Misc",
  },
  {
    id: "track-line-fill",
    name: "Track Line Fill",
    svg: `<i class="icon-track-fill\"></i>`,
    jsx: '<i className="icon-track-fill"></i>',
    category: "Misc",
  },
  {
    id: "track-line-line",
    name: "Track Line Line",
    svg: `<i class="icon-track-line\"></i>`,
    jsx: '<i className="icon-track-line"></i>',
    category: "Misc",
  },
  {
    id: "train-fill",
    name: "Train Fill",
    svg: `<i class="icon-train-fill\"></i>`,
    jsx: '<i className="icon-train-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "train-line",
    name: "Train Line",
    svg: `<i class="icon-train-line\"></i>`,
    jsx: '<i className="icon-train-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "travel-agency-fill",
    name: "Travel Agency Fill",
    svg: `<i class="icon-travel-agenc-fill\"></i>`,
    jsx: '<i className="icon-travel-agenc-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "travel-agency-line",
    name: "Travel Agency Line",
    svg: `<i class="icon-travel-agency-line\"></i>`,
    jsx: '<i className="icon-travel-agency-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "tree-fence-fill",
    name: "Tree Fence Fill",
    svg: `<i class="icon-tree-fence-fill\"></i>`,
    jsx: '<i className="icon-tree-fence-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "tree-fence-line",
    name: "Tree Fence Line",
    svg: `<i class="icon-tree-fence-line\"></i>`,
    jsx: '<i className="icon-tree-fence-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "trolly-fill",
    name: "Trolly Fill",
    svg: `<i class="icon-trolly-fill\"></i>`,
    jsx: '<i className="icon-trolly-fill"></i>',
    category: "Services",
  },
  {
    id: "trolly-line",
    name: "Trolly Line",
    svg: `<i class="icon-trolly-line\"></i>`,
    jsx: '<i className="icon-trolly-line"></i>',
    category: "Services",
  },
  {
    id: "tv-fill",
    name: "TV Fill",
    svg: `<i class="icon-tv-fill"></i>`,
    jsx: '<i className="icon-tv-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "tv-line",
    name: "TV Line",
    svg: `<i class="icon-tv-line"></i>`,
    jsx: '<i className="icon-tv-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "umbrella-fill",
    name: "Umbrella Fill",
    svg: `<i class="icon-umbrella-fill\"></i>`,
    jsx: '<i className="icon-umbrella-fill"></i>',
    category: "Misc",
  },
  {
    id: "umbrella-line",
    name: "Umbrella Line",
    svg: `<i class="icon-umbrella-line\"></i>`,
    jsx: '<i className="icon-umbrella-line"></i>',
    category: "Misc",
  },
  {
    id: "upgrade-fill",
    name: "Upgrade Fill",
    svg: `<i class="icon-upgrade-fill\"></i>`,
    jsx: '<i className="icon-upgrade-fill"></i>',
    category: "Services",
  },
  {
    id: "upgrade-line",
    name: "Upgrade Line",
    svg: `<i class="icon-upgrade-line\"></i>`,
    jsx: '<i className="icon-upgrade-line"></i>',
    category: "Services",
  },
  {
    id: "vaccume-fill",
    name: "Vaccume Fill",
    svg: `<i class="icon-vaccume-fill\"></i>`,
    jsx: '<i className="icon-vaccume-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "vaccume-line",
    name: "Vaccume Line",
    svg: `<i class="icon-vaccume-line\"></i>`,
    jsx: '<i className="icon-vaccume-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "vault-fill",
    name: "Vault Fill",
    svg: `<i class="icon-vault-fill\"></i>`,
    jsx: '<i className="icon-vault-fill"></i>',
    category: "Misc",
  },
  {
    id: "vault-line",
    name: "Vault Line",
    svg: `<i class="icon-vault-line\"></i>`,
    jsx: '<i className="icon-vault-line"></i>',
    category: "Misc",
  },
  {
    id: "vending-machine-fill",
    name: "Vending Machine Fill",
    svg: `<i class="icon-vending-machine-fill\"></i>`,
    jsx: '<i className="icon-vending-machine-fill"></i>',
    category: "Facilities",
  },
  {
    id: "vending-machine-line",
    name: "Vending Machine Line",
    svg: `<i class="icon-vending-machine-line\"></i>`,
    jsx: '<i className="icon-vending-machine-line"></i>',
    category: "Facilities",
  },
  {
    id: "video-slash-fill",
    name: "Video Slash Fill",
    svg: `<i class="icon-video-slash-fill\"></i>`,
    jsx: '<i className="icon-video-slash-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "video-slash-line",
    name: "Video Slash Line",
    svg: `<i class="icon-video-slash-line\"></i>`,
    jsx: '<i className="icon-video-slash-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "video-tapes-fill",
    name: "Video Tapes Fill",
    svg: `<i class="icon-video-tapes-fill\"></i>`,
    jsx: '<i className="icon-video-tapes-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "video-tapes-line",
    name: "Video Tapes Line",
    svg: `<i class="icon-video-tapes-line\"></i>`,
    jsx: '<i className="icon-video-tapes-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "water-purifier-fill",
    name: "Water Purifier Fill",
    svg: `<i class="icon-water-purifier-fill"></i>`,
    jsx: '<i className="icon-water-purifier-fill"></i>',
    category: "Facilities",
  },
  {
    id: "water-purifier-line",
    name: "Water Purifier Line",
    svg: `<i class="icon-water-purifier-line"></i>`,
    jsx: '<i className="icon-water-purifier-line"></i>',
    category: "Facilities",
  },
  {
    id: "water-skiing-fill",
    name: "Water Skiing Fill",
    svg: `<i class="icon-water-skiing-fill\"></i>`,
    jsx: '<i className="icon-water-skiing-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "water-skiing-line",
    name: "Water Skiing Line",
    svg: `<i class="icon-water-skiing-line\"></i>`,
    jsx: '<i className="icon-water-skiing-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "washing-machine-fill",
    name: "Washing Machine Fill",
    svg: `<i class="icon-washing-machine-fill\"></i>`,
    jsx: '<i className="icon-washing-machine-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "washing-machine-line",
    name: "Washing Machine Line",
    svg: `<i class="icon-washing-machine-line\"></i>`,
    jsx: '<i className="icon-washing-machine-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "wedding-fill",
    name: "Wedding Fill",
    svg: `<i class="icon-wedding-fill\"></i>`,
    jsx: '<i className="icon-wedding-fill"></i>',
    category: "Misc",
  },
  {
    id: "wedding-line",
    name: "Wedding Line",
    svg: `<i class="icon-wedding-line\"></i>`,
    jsx: '<i className="icon-wedding-line"></i>',
    category: "Misc",
  },
  {
    id: "wheel-chair-fill",
    name: "Wheel Chair Fill",
    svg: `<i class="icon-wheel-chair-fill\"></i>`,
    jsx: '<i className="icon-wheel-chair-fill"></i>',
    category: "Misc",
  },
  {
    id: "wheel-chair-line",
    name: "Wheel Chair Line",
    svg: `<i class="icon-wheel-chair-line\"></i>`,
    jsx: '<i className="icon-wheel-chair-line"></i>',
    category: "Misc",
  },
  {
    id: "whirlpool-fill",
    name: "Whirlpool Fill",
    svg: `<i class="icon-wirlpool-fill\"></i>`,
    jsx: '<i className="icon-wirlpool-fill"></i>',
    category: "Leisure & Amenities",
  },
  {
    id: "whirlpool-line",
    name: "Whirlpool Line",
    svg: `<i class="icon-wirlpool-line\"></i>`,
    jsx: '<i className="icon-wirlpool-line"></i>',
    category: "Leisure & Amenities",
  },
  {
    id: "wi-fi-fill",
    name: "Wi Fi Fill",
    svg: `<i class="icon-wi-fi-fill\"></i>`,
    jsx: '<i className="icon-wi-fi-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "wi-fi-line",
    name: "Wi Fi Line",
    svg: `<i class="icon-wi-fi-line\"></i>`,
    jsx: '<i className="icon-wi-fi-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "wine-glass-fill",
    name: "Wine Glass Fill",
    svg: `<i class="icon-wine-glass-fill\"></i>`,
    jsx: '<i className="icon-wine-glass-fill"></i>',
    category: "Misc",
  },
  {
    id: "wine-glass-line",
    name: "Wine Glass Line",
    svg: `<i class="icon-wine-glass-line\"></i>`,
    jsx: '<i className="icon-wine-glass-line"></i>',
    category: "Misc",
  },
  {
    id: "wrench-fill",
    name: "Wrench Fill",
    svg: `<i class="icon-wrench-fill"></i>`,
    jsx: '<i className="icon-wrench-fill"></i>',
    category: "Facilities",
  },
  {
    id: "wrench-line",
    name: "Wrench Line",
    svg: `<i class="icon-wrench-line"></i>`,
    jsx: '<i className="icon-wrench-line"></i>',
    category: "Facilities",
  },
];
