export interface Icon {
  id: string;
  name: string;
  svg: string;
  jsx: string;
  category: string;
}

export const icons: Icon[] = [
  {
    id: "ac-fill",
    name: "Ac Fill",
    svg: `<i class="icon-ac-fill"></i>`,
    jsx: '<i className="icon-ac-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "ac-line",
    name: "Ac Line",
    svg: `<i class="icon-ac-line"></i>`,
    jsx: '<i className="icon-ac-line"></i>',
    category: "Accommodation",
  },
  {
    id: "adjoining-room-fill",
    name: "Adjoining Room Fill",
    svg: `<i class="icon-adjoining-room-fill"></i>`,
    jsx: '<i className="icon-adjoining-room-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "adjoining-room-line",
    name: "Adjoining Room Line",
    svg: `<i class="icon-adjoining-room-line"></i>`,
    jsx: '<i className="icon-adjoining-room-line"></i>',
    category: "Accommodation",
  },
  {
    id: "corridor-fill",
    name: "Corridor Fill",
    svg: `<i class="icon-corridor-fill"></i>`,
    jsx: '<i className="icon-corridor-fill"></i>',
    category: "Accommodation",
  },
  {
    id: "corridor-line",
    name: "Corridor Line",
    svg: `<i class="icon-corridor-line"></i>`,
    jsx: '<i className="icon-corridor-line"></i>',
    category: "Accommodation",
  },
  // Services
  {
    id: "alarm-fill",
    name: "Alarm Fill",
    svg: `<i class="icon-alarm-fill"></i>`,
    jsx: '<i className="icon-alarm-fill"></i>',
    category: "Services",
  },
  {
    id: "alarm-line",
    name: "Alarm Line",
    svg: `<i class="icon-alarm-line"></i>`,
    jsx: '<i className="icon-alarm-line"></i>',
    category: "Services",
  },
  {
    id: "atm-fill",
    name: "Atm Fill",
    svg: `<i class="icon-atm-fill"></i>`,
    jsx: '<i className="icon-atm-fill"></i>',
    category: "Services",
  },
  {
    id: "atm-line",
    name: "Atm Line",
    svg: `<i class="icon-atm-line"></i>`,
    jsx: '<i className="icon-atm-line"></i>',
    category: "Services",
  },
  {
    id: "bell-boy-fill",
    name: "Bell Boy Fill",
    svg: `<i class="icon-bell-boy-fill"></i>`,
    jsx: '<i className="icon-bell-boy-fill"></i>',
    category: "Services",
  },
  {
    id: "bell-boy-line",
    name: "Bell Boy Line",
    svg: `<i class="icon-bell-boy-line"></i>`,
    jsx: '<i className="icon-bell-boy-line"></i>',
    category: "Services",
  },
  {
    id: "call-bell-fill",
    name: "Call Bell Fill",
    svg: `<i class="icon-call-bell-fill"></i>`,
    jsx: '<i className="icon-call-bell-fill"></i>',
    category: "Services",
  },
  {
    id: "call-bell-line",
    name: "Call Bell Line",
    svg: `<i class="icon-call-bell-line"></i>`,
    jsx: '<i className="icon-call-bell-line"></i>',
    category: "Services",
  },
  {
    id: "door-man-fill",
    name: "Door Man Fill",
    svg: `<i class="icon-door-man-fill"></i>`,
    jsx: '<i className="icon-door-man-fill"></i>',
    category: "Services",
  },
  {
    id: "door-man-line",
    name: "Door Man Line",
    svg: `<i class="icon-door-man-line"></i>`,
    jsx: '<i className="icon-door-man-line"></i>',
    category: "Services",
  },
  {
    id: "front-office-fill",
    name: "Front Office Fill",
    svg: `<i class="icon-front-office-fill"></i>`,
    jsx: '<i className="icon-front-office-fill"></i>',
    category: "Services",
  },
  {
    id: "front-office-line",
    name: "Front Office Line",
    svg: `<i class="icon-front-office-line"></i>`,
    jsx: '<i className="icon-front-office-line"></i>',
    category: "Services",
  },
  // Food & Dining
  {
    id: "bbq-fill",
    name: "Bbq Fill",
    svg: `<i class="icon-bbq-fill"></i>`,
    jsx: '<i className="icon-bbq-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "bbq-line",
    name: "Bbq Line",
    svg: `<i class="icon-bbq-line"></i>`,
    jsx: '<i className="icon-bbq-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "bar-fill",
    name: "Bar Fill",
    svg: `<i class="icon-bar-fill"></i>`,
    jsx: '<i className="icon-bar-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "bar-line",
    name: "Bar Line",
    svg: `<i class="icon-bar-line"></i>`,
    jsx: '<i className="icon-bar-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "burger-fill",
    name: "Burger Fill",
    svg: `<i class="icon-burger-fill"></i>`,
    jsx: '<i className="icon-burger-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "burger-line",
    name: "Burger Line",
    svg: `<i class="icon-burger-line"></i>`,
    jsx: '<i className="icon-burger-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "catering-fill",
    name: "Catering Fill",
    svg: `<i class="icon-catering-fill"></i>`,
    jsx: '<i className="icon-catering-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "catering-line",
    name: "Catering Line",
    svg: `<i class="icon-catering-line"></i>`,
    jsx: '<i className="icon-catering-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "chef-hat-fill",
    name: "Chef Hat Fill",
    svg: `<i class="icon-chef-hat-fill"></i>`,
    jsx: '<i className="icon-chef-hat-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "chef-hat-line",
    name: "Chef Hat Line",
    svg: `<i class="icon-chef-hat-line"></i>`,
    jsx: '<i className="icon-chef-hat-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "coffee-cup-fill",
    name: "Coffee Cup Fill",
    svg: `<i class="icon-coffee-cup-fill"></i>`,
    jsx: '<i className="icon-coffee-cup-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "coffee-line",
    name: "Coffee Line",
    svg: `<i class="icon-coffee-line"></i>`,
    jsx: '<i className="icon-coffee-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "coking-pot-fill",
    name: "Coking Pot Fill",
    svg: `<i class="icon-coking-pot-fill"></i>`,
    jsx: '<i className="icon-coking-pot-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "coking-pot-line",
    name: "Coking Pot Line",
    svg: `<i class="icon-coking-pot-line"></i>`,
    jsx: '<i className="icon-coking-pot-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "diet-fill",
    name: "Diet Fill",
    svg: `<i class="icon-diet-fill"></i>`,
    jsx: '<i className="icon-diet-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "diet-line",
    name: "Diet Line",
    svg: `<i class="icon-diet-line"></i>`,
    jsx: '<i className="icon-diet-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "dish-fill",
    name: "Dish Fill",
    svg: `<i class="icon-dish-fill"></i>`,
    jsx: '<i className="icon-dish-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "dish-line",
    name: "Dish Line",
    svg: `<i class="icon-dish-line"></i>`,
    jsx: '<i className="icon-dish-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "grill-fill",
    name: "Grill Fill",
    svg: `<i class="icon-grill-fill"></i>`,
    jsx: '<i className="icon-grill-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "grill-line",
    name: "Grill Line",
    svg: `<i class="icon-grill-line"></i>`,
    jsx: '<i className="icon-grill-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "knife-fork-fill",
    name: "Knife Fork Fill",
    svg: `<i class="icon-knife-fork-fill"></i>`,
    jsx: '<i className="icon-knife-fork-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "knife-fork-line",
    name: "Knife Fork Line",
    svg: `<i class="icon-knife-fork-line"></i>`,
    jsx: '<i className="icon-knife-fork-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "liquor-fill",
    name: "Liquor Fill",
    svg: `<i class="icon-liquor-fill"></i>`,
    jsx: '<i className="icon-liquor-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "liquor-line",
    name: "Liquor Line",
    svg: `<i class="icon-liquor-line"></i>`,
    jsx: '<i className="icon-liquor-line"></i>',
    category: "Food & Dining",
  },
  {
    id: "menu-fill",
    name: "Menu Fill",
    svg: `<i class="icon-menu-fill"></i>`,
    jsx: '<i className="icon-menu-fill"></i>',
    category: "Food & Dining",
  },
  {
    id: "menu-line",
    name: "Menu Line",
    svg: `<i class="icon-menu-line"></i>`,
    jsx: '<i className="icon-menu-line"></i>',
    category: "Food & Dining",
  },
  // Shopping
  {
    id: "baby-dress-fill",
    name: "Baby Dress Fill",
    svg: `<i class="icon-baby-dress-fill"></i>`,
    jsx: '<i className="icon-baby-dress-fill"></i>',
    category: "Shopping",
  },
  {
    id: "baby-dress-line",
    name: "Baby Dress Line",
    svg: `<i class="icon-baby-dress-line"></i>`,
    jsx: '<i className="icon-baby-dress-line"></i>',
    category: "Shopping",
  },
  {
    id: "dress-fill",
    name: "Dress Fill",
    svg: `<i class="icon-dress-fill"></i>`,
    jsx: '<i className="icon-dress-fill"></i>',
    category: "Shopping",
  },
  {
    id: "dress-line",
    name: "Dress Line",
    svg: `<i class="icon-dress-line"></i>`,
    jsx: '<i className="icon-dress-line"></i>',
    category: "Shopping",
  },
  {
    id: "shop-fill",
    name: "Shop Fill",
    svg: `<i class="icon-shop-fill"></i>`,
    jsx: '<i className="icon-shop-fill"></i>',
    category: "Shopping",
  },
  {
    id: "shop-line",
    name: "Shop Line",
    svg: `<i class="icon-shop-line"></i>`,
    jsx: '<i className="icon-shop-line"></i>',
    category: "Shopping",
  },
  {
    id: "shopping-bag-fill",
    name: "Shopping Bag Fill",
    svg: `<i class="icon-shopping-bag-fill"></i>`,
    jsx: '<i className="icon-shopping-bag-fill"></i>',
    category: "Shopping",
  },
  {
    id: "shopping-bag-line",
    name: "Shopping Bag Line",
    svg: `<i class="icon-shopping-bag-line"></i>`,
    jsx: '<i className="icon-shopping-bag-line"></i>',
    category: "Shopping",
  },
  // Housekeeping
  {
    id: "broom-fill",
    name: "Broom Fill",
    svg: `<i class="icon-broom-fill"></i>`,
    jsx: '<i className="icon-broom-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "broom-line",
    name: "Broom Line",
    svg: `<i class="icon-broom-line"></i>`,
    jsx: '<i className="icon-broom-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "carpet-fill",
    name: "Carpet Fill",
    svg: `<i class="icon-carpet-fill"></i>`,
    jsx: '<i className="icon-carpet-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "carpet-line",
    name: "Carpet Line",
    svg: `<i class="icon-carpet-line"></i>`,
    jsx: '<i className="icon-carpet-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "dry-clean-fill",
    name: "Dry Clean Fill",
    svg: `<i class="icon-dry-clean-fill"></i>`,
    jsx: '<i className="icon-dry-clean-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "dry-clean-line",
    name: "Dry Clean Line",
    svg: `<i class="icon-dry-clean-line"></i>`,
    jsx: '<i className="icon-dry-clean-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "dryer-fill",
    name: "Dryer Fill",
    svg: `<i class="icon-dryer-fill"></i>`,
    jsx: '<i className="icon-dryer-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "dryer-line",
    name: "Dryer Line",
    svg: `<i class="icon-dryer-line"></i>`,
    jsx: '<i className="icon-dryer-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "ironing-board-fill",
    name: "Ironing Board Fill",
    svg: `<i class="icon-ironing-board-fill"></i>`,
    jsx: '<i className="icon-ironing-board-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "ironing-board-line",
    name: "Ironing Board Line",
    svg: `<i class="icon-ironing-board-line"></i>`,
    jsx: '<i className="icon-ironing-board-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "vaccume-fill",
    name: "Vaccume Fill",
    svg: `<i class="icon-vaccume-fill"></i>`,
    jsx: '<i className="icon-vaccume-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "vaccume-line",
    name: "Vaccume Line",
    svg: `<i class="icon-vaccume-line"></i>`,
    jsx: '<i className="icon-vaccume-line"></i>',
    category: "Housekeeping",
  },
  {
    id: "washing-machine-fill",
    name: "Washing Machine Fill",
    svg: `<i class="icon-washing-machine-fill"></i>`,
    jsx: '<i className="icon-washing-machine-fill"></i>',
    category: "Housekeeping",
  },
  {
    id: "washing-machine-line",
    name: "Washing Machine Line",
    svg: `<i class="icon-washing-machine-line"></i>`,
    jsx: '<i className="icon-washing-machine-line"></i>',
    category: "Housekeeping",
  },
  // Finance
  {
    id: "bank-fill",
    name: "Bank Fill",
    svg: `<i class="icon-bank-fill"></i>`,
    jsx: '<i className="icon-bank-fill"></i>',
    category: "Finance",
  },
  {
    id: "bank-line",
    name: "Bank Line",
    svg: `<i class="icon-bank-line"></i>`,
    jsx: '<i className="icon-bank-line"></i>',
    category: "Finance",
  },
  {
    id: "cheque-fill",
    name: "Cheque Fill",
    svg: `<i class="icon-cheque-fill"></i>`,
    jsx: '<i className="icon-cheque-fill"></i>',
    category: "Finance",
  },
  {
    id: "cheque-line",
    name: "Cheque Line",
    svg: `<i class="icon-cheque-line"></i>`,
    jsx: '<i className="icon-cheque-line"></i>',
    category: "Finance",
  },
  // Security & Safety
  {
    id: "no-smoking-fill",
    name: "No Smokin Fill",
    svg: `<i class="icon-no-smokin-fill"></i>`,
    jsx: '<i className="icon-no-smokin-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "no-smoking-line",
    name: "No Smoking Line",
    svg: `<i class="icon-no-smoking-line"></i>`,
    jsx: '<i className="icon-no-smoking-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "security-fill",
    name: "Security Fill",
    svg: `<i class="icon-security-fill"></i>`,
    jsx: '<i className="icon-security-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "security-line",
    name: "Security Line",
    svg: `<i class="icon-security-line"></i>`,
    jsx: '<i className="icon-security-line"></i>',
    category: "Security & Safety",
  },
  {
    id: "shield-check-fill",
    name: "Shield Check Fill",
    svg: `<i class="icon-shield-check-fill"></i>`,
    jsx: '<i className="icon-shield-check-fill"></i>',
    category: "Security & Safety",
  },
  {
    id: "shield-check-line",
    name: "Shield Check Line",
    svg: `<i class="icon-shield-check-line"></i>`,
    jsx: '<i className="icon-shield-check-line"></i>',
    category: "Security & Safety",
  },
  // Medical & Safety
  {
    id: "medical-fill",
    name: "Medical Fill",
    svg: `<i class="icon-medical-fill"></i>`,
    jsx: '<i className="icon-medical-fill"></i>',
    category: "Medical & Safety",
  },
  {
    id: "medical-line",
    name: "Medical Line",
    svg: `<i class="icon-medical-line"></i>`,
    jsx: '<i className="icon-medical-line"></i>',
    category: "Medical & Safety",
  },
  // Technology & Communication
  {
    id: "chat-fill",
    name: "Chat Fill",
    svg: `<i class="icon-chat-fill"></i>`,
    jsx: '<i className="icon-chat-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "chat-line",
    name: "Chat Line",
    svg: `<i class="icon-chat-line"></i>`,
    jsx: '<i className="icon-chat-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "hotspot-fill",
    name: "Hotspot Fill",
    svg: `<i class="icon-hotspot-fill"></i>`,
    jsx: '<i className="icon-hotspot-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "hotspot-line",
    name: "Hotspot Line",
    svg: `<i class="icon-hotspot-line"></i>`,
    jsx: '<i className="icon-hotspot-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "internet-fill",
    name: "Internet Fill",
    svg: `<i class="icon-internet-fill"></i>`,
    jsx: '<i className="icon-internet-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "internet-line",
    name: "Internet Line",
    svg: `<i class="icon-internet-line"></i>`,
    jsx: '<i className="icon-internet-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "wi-fi-fill",
    name: "Wi Fi Fill",
    svg: `<i class="icon-wi-fi-fill"></i>`,
    jsx: '<i className="icon-wi-fi-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "wi-fi-line",
    name: "Wi Fi Line",
    svg: `<i class="icon-wi-fi-line"></i>`,
    jsx: '<i className="icon-wi-fi-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "plug-fill",
    name: "Plug Fill",
    svg: `<i class="icon-plug-fill"></i>`,
    jsx: '<i className="icon-plug-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "plug-line",
    name: "Plug Line",
    svg: `<i class="icon-plug-line"></i>`,
    jsx: '<i className="icon-plug-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "printer-fill",
    name: "Printer Fill",
    svg: `<i class="icon-printer-fill"></i>`,
    jsx: '<i className="icon-printer-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "printer-line",
    name: "Printer Line",
    svg: `<i class="icon-printer-line"></i>`,
    jsx: '<i className="icon-printer-line"></i>',
    category: "Technology & Communication",
  },
  {
    id: "video-tapes-fill",
    name: "Video Tapes Fill",
    svg: `<i class="icon-video-tapes-fill"></i>`,
    jsx: '<i className="icon-video-tapes-fill"></i>',
    category: "Technology & Communication",
  },
  {
    id: "video-tapes-line",
    name: "Video Tapes Line",
    svg: `<i class="icon-video-tapes-line"></i>`,
    jsx: '<i className="icon-video-tapes-line"></i>',
    category: "Technology & Communication",
  },
  // Travel & Transportation
  {
    id: "cab-fill",
    name: "Cab Fill",
    svg: `<i class="icon-cab-fill"></i>`,
    jsx: '<i className="icon-cab-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "cab-line",
    name: "Cab Line",
    svg: `<i class="icon-cab-line"></i>`,
    jsx: '<i className="icon-cab-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "check-in-fill",
    name: "Check In Fill",
    svg: `<i class="icon-check-in-fill"></i>`,
    jsx: '<i className="icon-check-in-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "check-in-line",
    name: "Check In Line",
    svg: `<i class="icon-check-in-line"></i>`,
    jsx: '<i className="icon-check-in-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "check-out-fill",
    name: "Check Out Fill",
    svg: `<i class="icon-check-out-fill"></i>`,
    jsx: '<i className="icon-check-out-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "check-out-line",
    name: "Check Out Line",
    svg: `<i class="icon-check-out-line"></i>`,
    jsx: '<i className="icon-check-out-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "luggage-fill",
    name: "Luggage Fill",
    svg: `<i class="icon-luggage-fill"></i>`,
    jsx: '<i className="icon-luggage-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "luggage-line",
    name: "Luggage Line",
    svg: `<i class="icon-luggage-line"></i>`,
    jsx: '<i className="icon-luggage-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "parking-fill",
    name: "Parking Fill",
    svg: `<i class="icon-parking-fill"></i>`,
    jsx: '<i className="icon-parking-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "parking-line",
    name: "Parking Line",
    svg: `<i class="icon-parking-line"></i>`,
    jsx: '<i className="icon-parking-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "train-fill",
    name: "Train Fill",
    svg: `<i class="icon-train-fill"></i>`,
    jsx: '<i className="icon-train-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "train-line",
    name: "Train Line",
    svg: `<i class="icon-train-line"></i>`,
    jsx: '<i className="icon-train-line"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "travel-agenc-fill",
    name: "Travel Agenc Fill",
    svg: `<i class="icon-travel-agenc-fill"></i>`,
    jsx: '<i className="icon-travel-agenc-fill"></i>',
    category: "Travel & Transportation",
  },
  {
    id: "travel-agency-line",
    name: "Travel Agency Line",
    svg: `<i class="icon-travel-agency-line"></i>`,
    jsx: '<i className="icon-travel-agency-line"></i>',
    category: "Travel & Transportation",
  },
  // Outdoor & Activities
  {
    id: "beach-fill",
    name: "Beach Fill",
    svg: `<i class="icon-beach-fill"></i>`,
    jsx: '<i className="icon-beach-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "beach-line",
    name: "Beach Line",
    svg: `<i class="icon-beach-line"></i>`,
    jsx: '<i className="icon-beach-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "bon-fire-fill",
    name: "Bon Fire Fill",
    svg: `<i class="icon-bon-fire-fill"></i>`,
    jsx: '<i className="icon-bon-fire-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "bon-fire-line",
    name: "Bon Fire Line",
    svg: `<i class="icon-bon-fire-line"></i>`,
    jsx: '<i className="icon-bon-fire-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "court-fill",
    name: "Court Fill",
    svg: `<i class="icon-court-fill"></i>`,
    jsx: '<i className="icon-court-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "court-line",
    name: "Court Line",
    svg: `<i class="icon-court-line"></i>`,
    jsx: '<i className="icon-court-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "cycle-fill",
    name: "Cycle Fill",
    svg: `<i class="icon-cycle-fill"></i>`,
    jsx: '<i className="icon-cycle-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "cycle-line",
    name: "Cycle Line",
    svg: `<i class="icon-cycle-line"></i>`,
    jsx: '<i className="icon-cycle-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "fence-fill",
    name: "Fence Fill",
    svg: `<i class="icon-fence-fill"></i>`,
    jsx: '<i className="icon-fence-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "fence-line",
    name: "Fence Line",
    svg: `<i class="icon-fence-line"></i>`,
    jsx: '<i className="icon-fence-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "flower-fill",
    name: "Flower Fill",
    svg: `<i class="icon-flower-fill"></i>`,
    jsx: '<i className="icon-flower-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "flower-line",
    name: "Flower Line",
    svg: `<i class="icon-flower-line"></i>`,
    jsx: '<i className="icon-flower-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "golf-fill",
    name: "Golf Fill",
    svg: `<i class="icon-golf-fill"></i>`,
    jsx: '<i className="icon-golf-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "golf-line",
    name: "Golf Line",
    svg: `<i class="icon-golf-line"></i>`,
    jsx: '<i className="icon-golf-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "horse-fill",
    name: "Horse Fill",
    svg: `<i class="icon-horse-fill"></i>`,
    jsx: '<i className="icon-horse-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "horse-line",
    name: "Horse Line",
    svg: `<i class="icon-horse-line"></i>`,
    jsx: '<i className="icon-horse-line"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "park-fill",
    name: "Park Fill",
    svg: `<i class="icon-park-fill"></i>`,
    jsx: '<i className="icon-park-fill"></i>',
    category: "Outdoor & Activities",
  },
  {
    id: "park-line",
    name: "Park Line",
    svg: `<i class="icon-park-line"></i>`,
    jsx: '<i className="icon-park-line"></i>',
    category: "Outdoor & Activities",
  },
  // Entertainment & Leisure
  {
    id: "cards-duo-tone",
    name: "Cards Duo Tone",
    svg: `<i class="icon-cards-duo-tone"></i>`,
    jsx: '<i className="icon-cards-duo-tone"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "cards-line",
    name: "Cards Line",
    svg: `<i class="icon-cards-line"></i>`,
    jsx: '<i className="icon-cards-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "disco-fill",
    name: "Disco Fill",
    svg: `<i class="icon-disco-fill"></i>`,
    jsx: '<i className="icon-disco-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "disco-line",
    name: "Disco Line",
    svg: `<i class="icon-disco-line"></i>`,
    jsx: '<i className="icon-disco-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "game-fill",
    name: "Game Fill",
    svg: `<i class="icon-game-fill"></i>`,
    jsx: '<i className="icon-game-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "game-line",
    name: "Game Line",
    svg: `<i class="icon-game-line"></i>`,
    jsx: '<i className="icon-game-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "guitar-fill",
    name: "Guitar Fill",
    svg: `<i class="icon-guitar-fill"></i>`,
    jsx: '<i className="icon-guitar-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "guitar-line",
    name: "Guitar Line",
    svg: `<i class="icon-guitar-line"></i>`,
    jsx: '<i className="icon-guitar-line"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "speaker-fill",
    name: "Speaker Fill",
    svg: `<i class="icon-speaker-fill"></i>`,
    jsx: '<i className="icon-speaker-fill"></i>',
    category: "Entertainment & Leisure",
  },
  {
    id: "speaker-line",
    name: "Speaker Line",
    svg: `<i class="icon-speaker-line"></i>`,
    jsx: '<i className="icon-speaker-line"></i>',
    category: "Entertainment & Leisure",
  },
  // Wellness & Relaxation
  {
    id: "gym-fill",
    name: "Gym Fill",
    svg: `<i class="icon-gym-fill"></i>`,
    jsx: '<i className="icon-gym-fill"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "gym-line",
    name: "Gym Line",
    svg: `<i class="icon-gym-line"></i>`,
    jsx: '<i className="icon-gym-line"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "jacuzzi-fill",
    name: "Jacuzzi Fill",
    svg: `<i class="icon-jacuzzi-fill"></i>`,
    jsx: '<i className="icon-jacuzzi-fill"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "jacuzzi-line",
    name: "Jacuzzi Line",
    svg: `<i class="icon-jacuzzi-line"></i>`,
    jsx: '<i className="icon-jacuzzi-line"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "sauna-fill",
    name: "Sauna Fill",
    svg: `<i class="icon-sauna-fill"></i>`,
    jsx: '<i className="icon-sauna-fill"></i>',
    category: "Wellness & Relaxation",
  },
  {
    id: "sauna-line",
    name: "Sauna Line",
    svg: `<i class="icon-sauna-line"></i>`,
    jsx: '<i className="icon-sauna-line"></i>',
    category: "Wellness & Relaxation",
  },
  // Facilities
  {
    id: "electric-outlet-fill",
    name: "Electric Outlet Fill",
    svg: `<i class="icon-electric-outlet-fill"></i>`,
    jsx: '<i className="icon-electric-outlet-fill"></i>',
    category: "Facilities",
  },
  {
    id: "electric-outlet-line",
    name: "Electric Outlet Line",
    svg: `<i class="icon-electric-outlet-line"></i>`,
    jsx: '<i className="icon-electric-outlet-line"></i>',
    category: "Facilities",
  },
  {
    id: "lift-fill",
    name: "Lift Fill",
    svg: `<i class="icon-lift-fill"></i>`,
    jsx: '<i className="icon-lift-fill"></i>',
    category: "Facilities",
  },
  {
    id: "lift-line",
    name: "Lift Line",
    svg: `<i class="icon-lift-line"></i>`,
    jsx: '<i className="icon-lift-line"></i>',
    category: "Facilities",
  },
  {
    id: "sofa-fill",
    name: "Sofa Fill",
    svg: `<i class="icon-sofa-fill"></i>`,
    jsx: '<i className="icon-sofa-fill"></i>',
    category: "Facilities",
  },
  {
    id: "sofa-line",
    name: "Sofa Line",
    svg: `<i class="icon-sofa-line"></i>`,
    jsx: '<i className="icon-sofa-line"></i>',
    category: "Facilities",
  },
  {
    id: "storage-fill",
    name: "Storage Fill",
    svg: `<i class="icon-storage-fill"></i>`,
    jsx: '<i className="icon-storage-fill"></i>',
    category: "Facilities",
  },
  {
    id: "storage-line",
    name: "Storage Line",
    svg: `<i class="icon-storage-line"></i>`,
    jsx: '<i className="icon-storage-line"></i>',
    category: "Facilities",
  },
  // Outdoor Condition
  {
    id: "snow-flake-fill",
    name: "Snow Flake Fill",
    svg: `<i class="icon-snow-flake-fill"></i>`,
    jsx: '<i className="icon-snow-flake-fill"></i>',
    category: "Outdoor Condition",
  },
  {
    id: "snow-flake-line",
    name: "Snow Flake Line",
    svg: `<i class="icon-snow-flake-line"></i>`,
    jsx: '<i className="icon-snow-flake-line"></i>',
    category: "Outdoor Condition",
  },
  {
    id: "sun-set-fill",
    name: "Sun Set Fill",
    svg: `<i class="icon-sun-set-fill"></i>`,
    jsx: '<i className="icon-sun-set-fill"></i>',
    category: "Outdoor Condition",
  },
  {
    id: "sun-set-line",
    name: "Sun Set Line",
    svg: `<i class="icon-sun-set-line"></i>`,
    jsx: '<i className="icon-sun-set-line"></i>',
    category: "Outdoor Condition",
  },
  // Leisure & Amenities
  {
    id: "swimming-pool-fill",
    name: "Swimming Pool Fill",
    svg: `<i class="icon-swimming-pool-fill"></i>`,
    jsx: '<i className="icon-swimming-pool-fill"></i>',
    category: "Leisure & Amenities",
  },
  {
    id: "swimming-pool-line",
    name: "Swimming Pool Line",
    svg: `<i class="icon-swimming-pool-line"></i>`,
    jsx: '<i className="icon-swimming-pool-line"></i>',
    category: "Leisure & Amenities",
  },
  {
    id: "whirlpool-fill",
    name: "Wirlpool Fill",
    svg: `<i class="icon-wirlpool-fill"></i>`,
    jsx: '<i className="icon-wirlpool-fill"></i>',
    category: "Leisure & Amenities",
  },
  {
    id: "whirlpool-line",
    name: "Wirlpool Line",
    svg: `<i class="icon-wirlpool-line"></i>`,
    jsx: '<i className="icon-wirlpool-line"></i>',
    category: "Leisure & Amenities",
  },
  // Health & Others
  {
    id: "baby-fill",
    name: "Baby Fill",
    svg: `<i class="icon-baby-fill"></i>`,
    jsx: '<i className="icon-baby-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "baby-line",
    name: "Baby Line",
    svg: `<i class="icon-baby-line"></i>`,
    jsx: '<i className="icon-baby-line"></i>',
    category: "Health & Others",
  },
  {
    id: "hour-glass-fill",
    name: "Hour Glass Fill",
    svg: `<i class="icon-hour-glass-fill"></i>`,
    jsx: '<i className="icon-hour-glass-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "hour-glass-line",
    name: "Hour Glass Line",
    svg: `<i class="icon-hour-glass-line"></i>`,
    jsx: '<i className="icon-hour-glass-line"></i>',
    category: "Health & Others",
  },
  {
    id: "phone-fill",
    name: "Phone Fill",
    svg: `<i class="icon-phone-fill"></i>`,
    jsx: '<i className="icon-phone-fill"></i>',
    category: "Health & Others",
  },
  {
    id: "phone-line",
    name: "Phone Line",
    svg: `<i class="icon-phone-line"></i>`,
    jsx: '<i className="icon-phone-line"></i>',
    category: "Health & Others",
  },
  // Misc
  {
    id: "box-fill",
    name: "Box Fill",
    svg: `<i class="icon-box-fill"></i>`,
    jsx: '<i className="icon-box-fill"></i>',
    category: "Misc",
  },
  {
    id: "box-line",
    name: "Box Line",
    svg: `<i class="icon-box-line"></i>`,
    jsx: '<i className="icon-box-line"></i>',
    category: "Misc",
  },
  {
    id: "briefcase-fill",
    name: "Briefcase Fill",
    svg: `<i class="icon-briefcase-fill"></i>`,
    jsx: '<i className="icon-briefcase-fill"></i>',
    category: "Misc",
  },
  {
    id: "briefcase-line",
    name: "Briefcase Line",
    svg: `<i class="icon-briefcase-line"></i>`,
    jsx: '<i className="icon-briefcase-line"></i>',
    category: "Misc",
  },
  {
    id: "group-fill",
    name: "Group Fill",
    svg: `<i class="icon-group-fill"></i>`,
    jsx: '<i className="icon-group-fill"></i>',
    category: "Misc",
  },
  {
    id: "group-line",
    name: "Group Line",
    svg: `<i class="icon-group-line"></i>`,
    jsx: '<i className="icon-group-line"></i>',
    category: "Misc",
  },
  {
    id: "language-fill",
    name: "Langauge Fill",
    svg: `<i class="icon-language-fill"></i>`,
    jsx: '<i className="icon-language-fill"></i>',
    category: "Misc",
  },
  {
    id: "language-line",
    name: "Langauge Line",
    svg: `<i class="icon-language-line"></i>`,
    jsx: '<i className="icon-language-line"></i>',
    category: "Misc",
  },
  {
    id: "newspaper-fill",
    name: "Newspaper Fill",
    svg: `<i class="icon-newspaper-fill"></i>`,
    jsx: '<i className="icon-newspaper-fill"></i>',
    category: "Misc",
  },
  {
    id: "newspaper-line",
    name: "Newspaper Line",
    svg: `<i class="icon-newspaper-line"></i>`,
    jsx: '<i className="icon-newspaper-line"></i>',
    category: "Misc",
  },
  {
    id: "smoking-fill",
    name: "Smoking Fill",
    svg: `<i class="icon-smoking-fill"></i>`,
    jsx: '<i className="icon-smoking-fill"></i>',
    category: "Misc",
  },
  {
    id: "smoking-line",
    name: "Smoking Line",
    svg: `<i class="icon-smoking-line"></i>`,
    jsx: '<i className="icon-smoking-line"></i>',
    category: "Misc",
  },
  {
    id: "spark-fill",
    name: "Spark Fill",
    svg: `<i class="icon-spark-fill"></i>`,
    jsx: '<i className="icon-spark-fill"></i>',
    category: "Misc",
  },
  {
    id: "spark-line",
    name: "Spark Line",
    svg: `<i class="icon-spark-line"></i>`,
    jsx: '<i className="icon-spark-line"></i>',
    category: "Misc",
  },
  {
    id: "toilet-fill",
    name: "Toilet Fill",
    svg: `<i class="icon-toilet-fill"></i>`,
    jsx: '<i className="icon-toilet-fill"></i>',
    category: "Misc",
  },
  {
    id: "toilet-line",
    name: "Toilet Line",
    svg: `<i class="icon-toilet-line"></i>`,
    jsx: '<i className="icon-toilet-line"></i>',
    category: "Misc",
  },
  {
    id: "track-fill",
    name: "Track Fill",
    svg: `<i class="icon-track-fill"></i>`,
    jsx: '<i className="icon-track-fill"></i>',
    category: "Misc",
  },
  {
    id: "track-line",
    name: "Track Line",
    svg: `<i class="icon-track-line"></i>`,
    jsx: '<i className="icon-track-line"></i>',
    category: "Misc",
  },
  {
    id: "vault-fill",
    name: "Vault Fill",
    svg: `<i class="icon-vault-fill"></i>`,
    jsx: '<i className="icon-vault-fill"></i>',
    category: "Misc",
  },
  {
    id: "vault-line",
    name: "Vault Line",
    svg: `<i class="icon-vault-line"></i>`,
    jsx: '<i className="icon-vault-line"></i>',
    category: "Misc",
  },
  {
    id: "wheel-chair-fill",
    name: "Wheel Chair Fill",
    svg: `<i class="icon-wheel-chair-fill"></i>`,
    jsx: '<i className="icon-wheel-chair-fill"></i>',
    category: "Misc",
  },
  {
    id: "wheel-chair-line",
    name: "Wheel Chair Line",
    svg: `<i class="icon-wheel-chair-line"></i>`,
    jsx: '<i className="icon-wheel-chair-line"></i>',
    category: "Misc",
  },
  {
    id: "wine-glass-fill",
    name: "Wine Glass Fill",
    svg: `<i class="icon-wine-glass-fill"></i>`,
    jsx: '<i className="icon-wine-glass-fill"></i>',
    category: "Misc",
  },
  {
    id: "wine-glass-line",
    name: "Wine Glass Line",
    svg: `<i class="icon-wine-glass-line"></i>`,
    jsx: '<i className="icon-wine-glass-line"></i>',
    category: "Misc",
  },
  {
    id: "wedding-fill",
    name: "Wedding Fill",
    svg: `<i class="icon-wedding-fill"></i>`,
    jsx: '<i className="icon-wedding-fill"></i>',
    category: "Misc",
  },
  {
    id: "wedding-line",
    name: "Wedding Line",
    svg: `<i class="icon-wedding-line"></i>`,
    jsx: '<i className="icon-wedding-line"></i>',
    category: "Misc",
  },
];
